/**
 * AUTO-GENERATED by scripts/migrate-jekyll-archive.ts from the archived Jekyll blog.
 * Do not hand-edit; re-run the script if the source content needs to change.
 */
export interface ArchivePostManifest {
  slug: string
  title: string
  publishedAt: string
  excerpt: string
  featuredImagePath?: string
  oldPermalink: string
}

export const archivePostsManifest: ArchivePostManifest[] = [
  {
    "slug": "az-elso-it-munkahely-4-resz",
    "title": "Az első IT munkahely – 4. rész",
    "publishedAt": "2023-01-09",
    "excerpt": "Az első IT munkahely sorozatunk harmadik részében elkezdtél dolgozni az első betanulós feladatodon, ami nagyobb falat, mint eredetileg gondoltad. Főleg miután beavatnak a helyi user acceptance…",
    "featuredImagePath": "/archive-images/az-elso-it-munkahely-4-resz/pexels-cottonbro-studio-5473957.jpg",
    "oldPermalink": "/2023/01/09/az-elso-it-munkahely-4-resz/"
  },
  {
    "slug": "az-elso-it-munkahely-3-resz",
    "title": "Az első IT munkahely – 3. rész",
    "publishedAt": "2023-01-05",
    "excerpt": "Az első IT munkahely sorozatunk második részében egy kis feladat keretében bejártad a fő monolit zegét-zugát, részt vettél egy grooming meetingen és megkaptad az első betanulós feladatodat, ami az…",
    "featuredImagePath": "/archive-images/az-elso-it-munkahely-3-resz/pexels-thisisengineering-3861958.jpg",
    "oldPermalink": "/2023/01/05/az-elso-it-munkahely-3-resz/"
  },
  {
    "slug": "az-elso-it-munkahely-2-resz",
    "title": "Az első IT munkahely – 2. rész",
    "publishedAt": "2022-12-21",
    "excerpt": "Az első IT munkahely sorozatunk első részében megérkeztél a céghez, bemutattak a tagoknak, megkaptad a céges laptopod, készen áll a fejlesztői környezet és már az alkalmazás is ott dübörög a gépeden.…",
    "featuredImagePath": "/archive-images/az-elso-it-munkahely-2-resz/pexels-markus-spiske-61903271.jpg",
    "oldPermalink": "/2022/12/21/az-elso-it-munkahely-2-resz/"
  },
  {
    "slug": "az-elso-it-munkahely-1-resz",
    "title": "Az első IT munkahely – 1. rész",
    "publishedAt": "2022-11-28",
    "excerpt": "Egy új munkahely szinte mindenkit izgalommal tölt el, pláne ha az egy teljesen másik iparág, mint ahol korábban dolgoztál. Egy bootcamp után még ingatag lábakon van a tudásod, de bízol magadban,…",
    "featuredImagePath": "/archive-images/az-elso-it-munkahely-1-resz/pexels-marc-mueller-3807691.jpg",
    "oldPermalink": "/2022/11/28/az-elso-it-munkahely-1-resz/"
  },
  {
    "slug": "dockerbe-zarva-1-resz",
    "title": "Dockerbe zárva – 1. rész",
    "publishedAt": "2022-09-06",
    "excerpt": "Akik nem egyetlen monolit alkalmazással dolgoznak éveken át, azok valószínűleg szembesültek már azzal a problémával, hogy bizony menedzselni kell az eszközök, fordítók, stb. verzióit a projektek és…",
    "featuredImagePath": "/archive-images/dockerbe-zarva-1-resz/contfail.bmp",
    "oldPermalink": "/2022/09/06/dockerbe-zarva-1-resz/"
  },
  {
    "slug": "terminalor-3-a-tmux-sessionok-lazadasa",
    "title": "Terminálor 3 – a tmux sessionök lázadása",
    "publishedAt": "2022-03-24",
    "excerpt": "A korábbi vim-es cikkem sikertelenségén felbuzdulva most egy újabb terminálhoz kapcsolódó cikkel érkezem, amivel remélhetőleg sikerül áttériteni pár olvasót a fekete alapon fehér oldalra. Figyelem!…",
    "featuredImagePath": "/archive-images/terminalor-3-a-tmux-sessionok-lazadasa/Screenshot-2022-03-24-at-14.39.35.png",
    "oldPermalink": "/2022/03/24/terminalor-3-a-tmux-sessionok-lazadasa/"
  },
  {
    "slug": "elotte-utana-cv-refaktoralas-programozoknak-interju",
    "title": "Előtte-utána: CV refaktorálás programozóknak + Interjú",
    "publishedAt": "2022-03-15",
    "excerpt": "A programozóknak széles körű készségekkel kell rendelkezniük ahhoz, hogy a munkahelyükön lévő sokféle feladatot a legmagasabb szakmai színvonalon eltudják látni. A leghatékonyabb fejlesztők a tudást,…",
    "featuredImagePath": "/archive-images/elotte-utana-cv-refaktoralas-programozoknak-interju/developercv_cover2.png",
    "oldPermalink": "/2022/03/15/elotte-utana-cv-refaktoralas-programozoknak-interju/"
  },
  {
    "slug": "a-portfolio-oldalak-szerepe-jelentosege-programozoknal-elso-munkahely",
    "title": "A portfólió oldalak szerepe, jelentősége programozóknál – első munkahely",
    "publishedAt": "2022-01-28",
    "excerpt": "A portfólió avagy referencia oldalak célja minden szakmában az, hogy bemutassa munkáinkat, tanulmányainkat, digitális önéletrajz is valamilyen szinten. De vajon szükség van-e erre ahhoz, hogy több…",
    "featuredImagePath": "/archive-images/a-portfolio-oldalak-szerepe-jelentosege-programozoknal-elso-munkahely/pexels-olia-danilevich-4974915-1.jpg",
    "oldPermalink": "/2022/01/28/a-portfolio-oldalak-szerepe-jelentosege-programozoknal-elso-munkahely/"
  },
  {
    "slug": "docker-as-a-linux-service",
    "title": "Docker as a (Linux) Service?",
    "publishedAt": "2021-09-30",
    "excerpt": "Konténereket elindítani könnyű, akár egy jól szituált shell script, akár docker-compose segítségével is, de egyes esetekben érdemes az adott hosztgép init system/process menedzserét használni. Mivel…",
    "featuredImagePath": "/archive-images/docker-as-a-linux-service/pexels-andrey-grushnikov-707676.jpg",
    "oldPermalink": "/2021/09/30/docker-as-a-linux-service/"
  },
  {
    "slug": "menedzseljuk-a-sajat-gepunket",
    "title": "Menedzseljük a saját gépünket!",
    "publishedAt": "2021-03-16",
    "excerpt": "Amikor új gépet kapunk a munkahelyen, az mindig egy jó érzés. Mire szép lassan belakjuk és letöltünk rá mindent: böngészőt, IDE-t, egyéb csomagokat, beállítgatjuk a háttérképet, Steamet, Spotify-t és…",
    "featuredImagePath": "/archive-images/menedzseljuk-a-sajat-gepunket/pexels-ramaz-bluashvili-6855582.jpg",
    "oldPermalink": "/2021/03/16/menedzseljuk-a-sajat-gepunket/"
  },
  {
    "slug": "php-80-az-opcache-tol-a-jit-ig-pt-ii",
    "title": "PHP 8.0 – Az OPCache-től a JIT-ig – Pt. II.",
    "publishedAt": "2020-12-29",
    "excerpt": "Az első rész itt megtalálható. A PHP 5.5-től kezdve a PHP 7.0-val és gyakorlatilag az azt követő minor verziókkal mind folyamatos performancia növekedést produkáltak a fejlesztők hol kisebb, hol…",
    "featuredImagePath": "/archive-images/php-80-az-opcache-tol-a-jit-ig-pt-ii/php8jit2-1.png",
    "oldPermalink": "/2020/12/29/php-8-0-az-opcache-tol-a-jit-ig-pt-ii/"
  },
  {
    "slug": "php-80-az-opcache-tol-a-jit-ig-pt-i",
    "title": "PHP 8.0 – Az OPCache-től a JIT-ig – Pt. I.",
    "publishedAt": "2020-12-24",
    "excerpt": "<div class=\"wp-block-group\"<div class=\"wp-block-groupinner-container is-layout-flow wp-block-group-is-layout-flow\"<div class=\"wp-block-group\"<div class=\"wp-block-groupinner-container is-layout-flow…",
    "featuredImagePath": "/archive-images/php-80-az-opcache-tol-a-jit-ig-pt-i/php8jit1-1.png",
    "oldPermalink": "/2020/12/24/php-8-0-az-opcache-tol-a-jit-ig-pt-1/"
  },
  {
    "slug": "asdf-a-fura-nevu-verziomenedzser",
    "title": "ASDF – a fura nevű verziómenedzser",
    "publishedAt": "2020-10-12",
    "excerpt": "TLDR; Az asdf képes menedzselni a rendszerünkön a globális és projekt specifikus verziókat, legyen az node, java, maven, kubectl vagy bármi. A github projekt itt található, ahol a leleményesebbek már…",
    "oldPermalink": "/2020/10/12/asdf-a-fura-nevu-verziomenedzser/"
  },
  {
    "slug": "vim-felturbozva",
    "title": "Vim felturbózva",
    "publishedAt": "2020-07-01",
    "excerpt": "A legutóbb volt egy bejegyzésem, ami arról szólt, hogy váltani készülök a menő IDE-k felől a Vim felé. Akkor még csak két hete játszadoztam vele, így túl sokat nem tudtam még nyilatkozni róla. Azóta…",
    "oldPermalink": "/2020/07/01/vim-felturbozva/"
  },
  {
    "slug": "ha-nem-ertesz-a-cobol",
    "title": "Ha nem értesz a COBOL",
    "publishedAt": "2020-04-12",
    "excerpt": "Aki mostanság figyeli a híreket, az biztos hallhatott róla, hogy az egyébként is kihalófélben lévő <skobaltbányászokból</s COBOL fejlesztőkből mégtöbbre van szükség, mert az USA munkaügyi segélyeket…",
    "oldPermalink": "/2020/04/12/ha-nem-ertessz-a-cobol/"
  },
  {
    "slug": "k3s-kubernetes-egyszeruen",
    "title": "k3s – Kubernetes egyszerűen?",
    "publishedAt": "2020-04-11",
    "excerpt": "Aki követi a munkásságomat tudja, hogy noha aláírom, hogy a Kubernetes tud hasznos lenni, óvatos optimizmussal közelítem meg a kérdést. Azt gondolom, hogy a nagy játékosok kivételével…",
    "oldPermalink": "/2020/04/11/k3s-kubernetes-egyszeruen/"
  },
  {
    "slug": "kalandozasok-vimmel",
    "title": "Kalandozások Vimmel",
    "publishedAt": "2020-04-04",
    "excerpt": "A szokásostól eltérő bejegyzés következik tőlem, mert ennek most nem feltétlenül a tudás átadása a célja, mintsem inkább egy kis történet, vagy épp folyamat megosztása. Ez a folyamat pedig nem más,…",
    "oldPermalink": "/2020/04/04/kalandozasok-vimmel/"
  },
  {
    "slug": "teszt-first",
    "title": "Teszt F.I.R.S.T",
    "publishedAt": "2020-03-15",
    "excerpt": "Automata teszteket írni szinte bárki tud. Jó teszteket írni viszont már közel sem. Na de mégis mitől lesz egy adott teszt jó? Itt nyílván elővehetnénk a tesztlefedettséget, netán azt, hogy mutációs…",
    "oldPermalink": "/2020/03/15/teszt-f-i-r-s-t/"
  },
  {
    "slug": "klasszikus-class",
    "title": "Klasszikus ::class",
    "publishedAt": "2020-02-12",
    "excerpt": "Az a csodálatos feladat hárult rám, hogy értesítsem az itt egybegyűlteket a PHP-s hírekről, újdonságokról, és egyéb finomságokról. És valljuk be, ez számomra nem esik túl távol. Mivel ez az első…",
    "oldPermalink": "/2020/02/12/klasszikus-class/"
  },
  {
    "slug": "a-teszteles-elveszett-elonye",
    "title": "A tesztelés elveszett előnye",
    "publishedAt": "2020-01-16",
    "excerpt": "Unit tesztelni jó. Rengeteg előnnyel jár, de valahogy nagyon sokan vannak akik még mindig utálják. Ezért nem a tesztelést kell hibáztatni, hanem azt, ahogy végezzük. (A cikkben több helyen a…",
    "oldPermalink": "/2020/01/16/a-teszteles-elveszett-elonye/"
  },
  {
    "slug": "java-kivetelek-checked-vagy-unchecked",
    "title": "Java kivételek – Checked vagy unchecked?",
    "publishedAt": "2020-01-15",
    "excerpt": "<figure class=\"wp-block-image\"</figureJava nyelvben kétféle kivételt különböztetünk meg: - Checked — ezek azok, amiket a compiler maga is ellenőríz. Amikor eldobod, akkor vagy helyben kezelned kell,…",
    "oldPermalink": "/2020/01/15/java-kivetelek-checked-vagy-unchecked/"
  },
  {
    "slug": "a-dummy-a-spy-es-a-tiz-kicsi-stub",
    "title": "A dummy, a spy, és a tíz kicsi stub",
    "publishedAt": "2020-01-09",
    "excerpt": "TL;DR Dummy: placeholder. Stub: metódusok visszatérési adatokkal előprogramozva. Spy: olyan stub, ami képes figyelni a felparaméterezett metódushívásokat. Mock: olyan spy, ami ellenőrzi is a hívások…",
    "oldPermalink": "/2020/01/09/a-dummy-a-spy-es-a-tiz-kicsi-stub/"
  },
  {
    "slug": "amit-elronthatunk-az-adapter-patternel",
    "title": "Amit elronthatunk az adapter patternel",
    "publishedAt": "2018-06-01",
    "excerpt": "Nemrégiben volt egy podcast epizódunk a függőségekről és arról, hogy melyiket is tudjuk leválasztani a domain logikánkról és mindezt hogyan. Ekkor említettük meg az adapter patternt, mint ideális…",
    "oldPermalink": "/2018/06/01/amit-elronthatunk-az-adapter-patternel/"
  },
  {
    "slug": "inversion-of-layered-architecture",
    "title": "Inversion of layered architecture",
    "publishedAt": "2017-10-28",
    "excerpt": "Hosszú ideje nem volt már technikai jellegű bejegyzés a blogon, épp itt az ideje kicsit változtatni ezen. A cikket az egyik stackoverflow kérdésre adott válaszom ihlette, ahol megkaptam, hogy a…",
    "oldPermalink": "/2017/10/28/inversion-of-layered-architecture/"
  },
  {
    "slug": "hogy-indult-a-podcastunk",
    "title": "Hogy indult a podcastünk?",
    "publishedAt": "2017-10-15",
    "excerpt": "Párszor felmerült már bennünk, hogy azok a témák, amikről egymás között beszélgetünk, meg kellene osztani másokkal. Pásztor János barátom hónapokkal ezelőtt rámírt facebook-on, azonban akkor még nem…",
    "oldPermalink": "/2017/10/15/hogy-indult-a-podcastunk/"
  },
  {
    "slug": "videoportal-keszenletben",
    "title": "Videóportál készenlétben",
    "publishedAt": "2017-07-27",
    "excerpt": "Hosszú ideje már, hogy utoljára írtam a blogra, lassacskán el is felejtem, hogy is kell ezt 🙂 Az elmúlt időszakban teljesen más volt fókuszban, mégpedig a <https://app.letscode.hu cím alatt…",
    "oldPermalink": "/2017/07/27/videoportal-keszenletben/"
  },
  {
    "slug": "logfajlok-pokla-2-mdc-keretrendszer-alatt",
    "title": "Logfájlok pokla 2. – MDC keretrendszer alatt",
    "publishedAt": "2017-05-13",
    "excerpt": "Az előző cikkben arról volt szó, hogy is tudjuk elszeparálni az egyes logbejegyzéseket az apache loggerével. Mint kiderült, van hasonló funkcionalitás a monologban is, csak ott még nem volt ekkora…",
    "oldPermalink": "/2017/05/13/logfajlok-pokla-2-mdc-keretrendszer-alatt/"
  },
  {
    "slug": "mit-tegyunk-ha-mar-elvesztunk-a-logfajlokban",
    "title": "Mit tegyünk ha már elvesztünk a logfájlokban?",
    "publishedAt": "2017-05-11",
    "excerpt": "Ismert a mondás, hogy a fejlesztők idejük 90%-ában debuggolnak, a másik 10%-ban pedig bugokat írnak. Ez utóbbi egy lokális/remote alkalmazás esetében még a nyelvspecifikus debuggerrel megoldható,…",
    "oldPermalink": "/2017/05/11/mit-tegyunk-ha-mar-elvesztunk-logfajlokban/"
  },
  {
    "slug": "sajat-cdn-kevesebb-mint-100-bol",
    "title": "Saját CDN kevesebb mint 100$-ból?",
    "publishedAt": "2017-04-12",
    "excerpt": "Aki dolgozott már velem az tudja, hogy ha egy mód van rá, nem a szokványos megoldásokat választom. Az elmúlt hónapok műszaki kalandozásai az Amazon Web Services tengereire sodortak, és a sok munka…",
    "oldPermalink": "/2017/04/12/sajat-cdn-kevesebb-mint-100-bol/"
  },
  {
    "slug": "circuit-breaker-avagy-mi-van-akkor-ha-nem-megy",
    "title": "Circuit breaker, avagy mi van akkor, ha nem megy?",
    "publishedAt": "2017-02-18",
    "excerpt": "Amikor szoftvert írunk, akkor törekszünk arra, hogy bolondbiztos legyen. Amikor webre fejlesztünk sem történik ez másként. Minden tőlünk telhetőt megteszünk annak érdekében, hogy bizony a felhasználó…",
    "oldPermalink": "/2017/02/18/circuit-breaker-avagy-mi-van-akkor-ha-nem-megy/"
  },
  {
    "slug": "laravel-dockerben",
    "title": "Laravel dockerben",
    "publishedAt": "2017-02-06",
    "excerpt": "A korábbiakban már láthattuk, hogy is tudunk apache alapú webszervert futtatni, azonban akadnak esetek, főleg ha a Laravel eszközkészletét vesszük figyelembe, mikor egy szimpla webszervernél több…",
    "oldPermalink": "/2017/02/06/laravel-dockerben/"
  },
  {
    "slug": "vissza-a-jovobe-legacy-kodok",
    "title": "Vissza a jövőbe – Legacy kódok",
    "publishedAt": "2017-01-30",
    "excerpt": "A mai nap az egyik facebook csoportban felröppent a kérdés, miszerint óhatatlanul is 'gány'-e minden kód, amit öröklünk. Az eddigi cikkekel ellentétben most nem fogunk hirtelen legacy kódot gyártani,…",
    "oldPermalink": "/2017/01/30/vissza-jovobe-legacy-kodok/"
  },
  {
    "slug": "soap-avagy-run-you-fools",
    "title": "SOAP, avagy ‘Run you fools!’",
    "publishedAt": "2017-01-23",
    "excerpt": "Az eddigi cikkekben főleg a RESTful irányába mentünk el, ami mostanában elterjedőben van, viszont óhatatlan, hogy az ember belefusson a jó öreg SOAP-ba. Már volt róla szó, hogy hogy is néz ki mindez,…",
    "oldPermalink": "/2017/01/23/soap-avagy-run-you-fools/"
  },
  {
    "slug": "ezeket-a-cikkeket-olvastatok-legtobben-2016-ban",
    "title": "Ezeket a cikkeket olvastátok legtöbben 2016-ban",
    "publishedAt": "2017-01-21",
    "excerpt": "Köszönöm, hogy 2016-ban is követtétek és olvastátok a Letscode.hu-t, remélhetőleg 2017-ben sem döntötök másképp. De mi is történt az elmúlt évben? Sajnos közel sem akadt annyi időm, mint terveztem,…",
    "oldPermalink": "/2017/01/21/ezeket-cikkeket-olvastatok-legtobben-2016-ban/"
  },
  {
    "slug": "konstrualjunk-web-api-t-passporticus-maximus",
    "title": "Konstruáljunk web API-t – Passporticus maximus",
    "publishedAt": "2017-01-15",
    "excerpt": "Az előző cikkben láthattuk, hogy az Apigility, habár nagyon sok mindenben megkönnyíti az ügyünket, amikor az OAuth dolgaira kerül a sor, itt sem ússzuk meg azt, hogy belemásszunk a rendszerbe. A…",
    "oldPermalink": "/2017/01/15/konstrualjunk-web-api-t-passporticus-maximus/"
  },
  {
    "slug": "php-docker-moge-bujva",
    "title": "PHP Docker mögé bújva",
    "publishedAt": "2016-12-31",
    "excerpt": "Ígértem korábban a Passportos verzióját a REST API-nk authentikációjához és ennek az első lépése az, hogy 5.3-as Laravel kell hozzá, ahol bele is futottam a hibába, miszerint lokálisan csak 5.6.3-as…",
    "oldPermalink": "/2016/12/31/php-docker-moge-bujva/"
  },
  {
    "slug": "pushbreaker-az-elet-ci-szerver-nelkul",
    "title": "Pushbreaker – Az élet CI szerver nélkül",
    "publishedAt": "2016-12-27",
    "excerpt": "Ha körbenézünk, hogy milyen/mekkora projekteken dolgozunk nap, mint nap (és itt főleg a kisebb projektekre gondolok), akkor számunkra is világos lesz, hogy bizony nem minden projekt érdemli meg azt,…",
    "oldPermalink": "/2016/12/27/pushbreaker-az-elet-ci-szerver-nelkul/"
  },
  {
    "slug": "oauth-20-apigility-modra",
    "title": "OAuth 2.0 Apigility módra",
    "publishedAt": "2016-12-22",
    "excerpt": "Habár legutóbbi cikkemben a Laraveles Passportot ígértem, gondoltam teszek egy próbát az Apigility átlal biztosított OAuth2.0-ás authentikációval is, részben azért, mert a B. Shaffer féle Oauth2…",
    "oldPermalink": "/2016/12/22/oauth-2-0-apigility-modra/"
  },
  {
    "slug": "hacklang-a-php-jovoje",
    "title": "Hacklang: a PHP jövője?",
    "publishedAt": "2016-12-20",
    "excerpt": "Aki dolgozott már velem az tudja, hogy szeretem a PHP-t. Rengeteg olyan előnye van, amit más nyelvekben egyáltalán nem lehet megtalálni. Emellett viszont van jónéhány hülyesége is, amitől minden…",
    "oldPermalink": "/2016/12/20/hacklang-a-php-jovoje/"
  },
  {
    "slug": "konstrualjunk-web-api-t-2-felvonas",
    "title": "Konstruáljunk web API-t – 2. felvonás",
    "publishedAt": "2016-12-19",
    "excerpt": "Amikor az ember webről beszél, a legtöbb esetben színes weboldalakat képzel el, ezerféle közösségi platform belépéssel, ahol az ember minden mozzanatát lépésen tudják követni különböző módszerekkel,…",
    "oldPermalink": "/2016/12/19/konstrualjunk-web-api-t-3-resz/"
  },
  {
    "slug": "angular-typescript-modra-3-resz",
    "title": "Angular Typescript módra – 3. rész",
    "publishedAt": "2016-12-04",
    "excerpt": "Az előző cikkben összeraktunk egy igen egyszerű statikus adatokat használó listázást. Jelenleg kegyetlenül vacakul fest, no meg a lényeg még nincs benne, a routing, amivel bele tudnánk navigálni az…",
    "oldPermalink": "/2016/12/04/angular-typescript-modra-3-resz/"
  },
  {
    "slug": "az-sql-injectionrol-egyszeruen",
    "title": "Az SQL injectionről egyszerűen",
    "publishedAt": "2016-12-04",
    "excerpt": "Ha régóta fejlesztesz, ez a téma valószínűleg a könyöködön jön ki. De épp a mai nap kaptam egy fájlt amiben egy egyetemi oktató által írt program volt és igen, 2016-ban volt benne SQL injection…",
    "oldPermalink": "/2016/12/04/sql-injectionrol-egyszeruen/"
  },
  {
    "slug": "learning-functional-programming-with-javascript-by-anjana-vakil",
    "title": "Learning Functional Programming with JavaScript by Anjana Vakil",
    "publishedAt": "2016-11-09",
    "excerpt": "\\[youtube id=\"e-5obm1G\\FY\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Nem jön be az objektum-orientált programozás? JavaScriptben programozol és nincs más választásod? Íme egy…",
    "oldPermalink": "/2016/11/09/learning-functional-programming-with-javascript-by-anjana-vakil/"
  },
  {
    "slug": "angular-2-typescript-modra-2-resz",
    "title": "Angular 2 TypeScript módra – 2. rész",
    "publishedAt": "2016-11-08",
    "excerpt": "Most, hogy megvan az angularos appunk alapja, nem ártana, hogy építsünk is valami értelmeset belőle. A todoAppokkal immáron Dunát lehetne rekeszteni, ezért most valami más irányba kellene elmenni.…",
    "oldPermalink": "/2016/11/08/angular-2-typescript-modra-2-resz/"
  },
  {
    "slug": "az-objektum-orientalt-programozas-alapjai",
    "title": "Az objektum-orientált programozás alapjai",
    "publishedAt": "2016-10-30",
    "excerpt": "Korábban már beszéltünk a haladó objektum-orientált programozás kérdéseiről, de azt hiszem, nem árt visszatérni az alapokhoz. Ma az objektum-orientált programozást vesézzük ki, egészen az alapoktól…",
    "oldPermalink": "/2016/10/30/az-objektum-orientalt-programozas-alapjai/"
  },
  {
    "slug": "megvaltoztathatatlan-objektumok",
    "title": "Megváltoztathatatlan objektumok",
    "publishedAt": "2016-10-18",
    "excerpt": "Objektum orientált programozásban gyakran használunk objektumokat adatok továbbítására. Ebben a cikkben egy olyan tervzési mintát szeretnék bemutatni, ami elsőre talán nem intuitív, de annál…",
    "oldPermalink": "/2016/10/18/megvaltoztathatatlan-objektumok/"
  },
  {
    "slug": "angular-2-typescript-modra-1-resz",
    "title": "Angular 2 TypeScript módra – 1. rész",
    "publishedAt": "2016-10-10",
    "excerpt": "Az előző cikkben kitértünk arra, hogy mi is az a TypeScript és miért is lehet a hasznunkra <delés, hogy eggyel növelhessük végre a használt tool-ok és supersetek sokaságát, mert ettől JS a JS</del. A…",
    "oldPermalink": "/2016/10/10/angular-2-typescript-modra/"
  },
  {
    "slug": "nyarvegi-nagytakaritas-weboldal-metaadatok",
    "title": "Nyárvégi nagytakarítás: Weboldal Metaadatok",
    "publishedAt": "2016-10-05",
    "excerpt": "Ahogy készül a Refaktor szép új motorja, kénytelenek voltunk kicsit foglalkozni azzal, hogy hogyan jelenik meg a közösségi médiában, keresőgépekben. Ahogy az lenni szokott, ahány szolgáltató, annyi…",
    "oldPermalink": "/2016/10/05/nyarvegi-nagytakaritas-weboldal-metaadatok/"
  },
  {
    "slug": "biztonsagos-jelszotarolas",
    "title": "Biztonságos jelszótárolás",
    "publishedAt": "2016-09-28",
    "excerpt": "Adott egy alkalmazás, ami felhasználói jelszavakat tárol, jelszóellenőrzés céljából. Igen ám, de mivel a a felhasználók többsége ugyanazt a jelszót használja több szolgáltatáshoz, ez igen kényes…",
    "oldPermalink": "/2016/09/28/biztonsagos-jelszotarolas/"
  },
  {
    "slug": "hypescript",
    "title": "HypeScript",
    "publishedAt": "2016-09-25",
    "excerpt": "A múltkori mobilos cikkre megkaptam, hogy inkább az Ionic 2-re vagy React Native-ra kellene fókuszálnom. A dolgot megfogadom, ám ahhoz, hogy az Ionic 2-re rátérhessünk, nem ártana végigjárni az utat…",
    "oldPermalink": "/2016/09/25/hypescript/"
  },
  {
    "slug": "cross-platform-mobilosodas-2-resz",
    "title": "Cross Platform mobilosodás – 2. rész",
    "publishedAt": "2016-09-18",
    "excerpt": "Az előző részben kitárgyaltuk hogy is lehet könnyen hibrid mobilalkalmazásokat készíteni, aztán szó esett a RESTful webservicek készítéséről is, amivel aztán ezt ki is tudjuk majd szolgálni. Most…",
    "oldPermalink": "/2016/09/18/cross-platform-mobilosodas-2-resz/"
  },
  {
    "slug": "tiszta-infrastruktura-4-resz-magas-rendelkezesre-allasu-rendszer-ket-gepbol",
    "title": "Tiszta infrastruktúra, 4. rész – Magas rendelkezésre állású rendszer két gépből?",
    "publishedAt": "2016-09-08",
    "excerpt": "A <acronym title=\"Hungarian Unix Portal\"HUP-on</acronym immáron sokadjára felmerült a kérdés, hogy hogyan lehetne két gépből magas rendelkezésre állású rendszert építeni? Ugorjunk fejest az ilyen…",
    "oldPermalink": "/2016/09/08/tiszta-infrastruktura-4-resz-magas-rendelkezesre-allasu-rendszer-ket-gepbol/"
  },
  {
    "slug": "konstrualjunk-web-api-t",
    "title": "Konstruáljunk Web API-t!",
    "publishedAt": "2016-08-26",
    "excerpt": "Amikor a legtöbben meghallják azt a rövidítést, hogy API, rendkívül különféle dolgokra asszociálnak. Van akinek a Java Persistence API jut eszébe, van akinek a Facebook API, míg másoknak valami…",
    "oldPermalink": "/2016/08/26/konstrualjunk-web-api-t-2/"
  },
  {
    "slug": "felreertett-programnyelvek-php",
    "title": "Félreértett programnyelvek: PHP",
    "publishedAt": "2016-08-17",
    "excerpt": "Talán meglepő egy ilyen cím 21 évvel a nyelv megjelenése után, de érdemes megnézni, hogy a világ harmadik legnagyobb oldalát hajtó technológia hova fejlődött az elmúlt pár évben. Félreértés ne essék:…",
    "oldPermalink": "/2016/08/17/felreertett-programnyelvek-php/"
  },
  {
    "slug": "tiszta-infrastruktura-3-resz-mit-monitorozzak",
    "title": "Tiszta infrastruktúra, 3. rész — Mit monitorozzak?",
    "publishedAt": "2016-08-09",
    "excerpt": "Lássuk be: egy nagyobb rendszert monitorozni kihívás. Amíg 4-5 egyszerű weboldalról könnyű megmondani, hogy működik-e, addig egy nagyobb, bonyolultabb infrastruktúra működési ellenőrzése már komoly…",
    "oldPermalink": "/2016/08/09/tiszta-infrastruktura-3-resz-mit-monitorozzak/"
  },
  {
    "slug": "tiszta-infrastruktura-2-resz-bevezetes-a-rendszerautomatizalasba",
    "title": "Tiszta infrastruktúra, 2. rész — Bevezetés a rendszerautomatizálásba",
    "publishedAt": "2016-07-27",
    "excerpt": "Számomra egy gyengén felépített infrastruktúra egyértelmű jele, amikor már egy SSH kulcs kimásolása is problémákba ütközik. Kézzel hegesztett konfigurációk, tarkabarka szerverek, kimaradt biztonsági…",
    "oldPermalink": "/2016/07/27/tiszta-infrastruktura-2-resz-bevezetes-a-rendszerautomatizalasba/"
  },
  {
    "slug": "cross-platform-mobilosodas-1-resz",
    "title": "Cross-Platform mobilosodás – 1. rész",
    "publishedAt": "2016-07-23",
    "excerpt": "Vannak dolgok, amik univerzálisak. Ilyen pl. a nevében is magában rejtő USB, az univerzális soros busz. Viszont nagyon sok esetben azt látjuk, hogy mindenki a saját kis dolgait erőlteti és emiatt…",
    "oldPermalink": "/2016/07/23/cross-platform-mobilosodas-1-resz/"
  },
  {
    "slug": "utoszo-a-tiszta-kod-sorozathoz",
    "title": "Utószó a Tiszta kód sorozathoz",
    "publishedAt": "2016-07-18",
    "excerpt": "A tiszta kód sorozat vége óta rengeteg visszajelzést kaptunk tőletek, és sokan kerestetek meg a különböző projektjeitekkel véleményt kérve. Frameworkök, függőségek A sorozatban többször is…",
    "oldPermalink": "/2016/07/18/utoszo-a-tiszta-kod-sorozathoz/"
  },
  {
    "slug": "law-of-demeter-ne-allj-szoba-idegennel",
    "title": "Law of Demeter – Ne állj szóba idegennel!",
    "publishedAt": "2016-07-17",
    "excerpt": "Az utolsó design cikkhez értünk, ez a SOLID utáni ráadás. Law of Demeter, más néven a principle of least knowledge egy ajánlás a szoftverfejlesztéshez, azon belül is az objektumorientált nyelvekhez.…",
    "oldPermalink": "/2016/07/17/ne-allj-szoba-idegennel/"
  },
  {
    "slug": "she-wants-the-di",
    "title": "She wants the DI",
    "publishedAt": "2016-07-16",
    "excerpt": "A SOLID sorozatunk utolsó része következik, ahol a Dependency Inversion Principle, röviden DIP lesz terítéken. Alkalmazásunk felépítését tekintve többszintű hierarchiát képez. Ha megvizsgáljuk az…",
    "oldPermalink": "/2016/07/16/she-wants-the-di/"
  },
  {
    "slug": "knitting-to-the-moon-a-holdraszallas-szamitogepei",
    "title": "Knitting to the Moon! — A holdraszállás számítógépei",
    "publishedAt": "2016-07-14",
    "excerpt": "\\[youtube id=\"f2ZCVnk-oRU\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Hogyan készítettek hordozható számítógépeket a holdraszálláshoz a 60-as években?",
    "oldPermalink": "/2016/07/14/knitting-to-the-moon-a-holdraszallas-szamitogepei/"
  },
  {
    "slug": "isp-interface-segregation-principle",
    "title": "ISP – Interface segregation principle",
    "publishedAt": "2016-07-09",
    "excerpt": "Amikor új applikáció tervezésébe kezdünk, akkor nem árt komolyan fontolóra venni, hogy milyen absztrakciókat is fogunk használni az egyes modulok és submodulok esetén. Ha ezen modulok egyike…",
    "oldPermalink": "/2016/07/09/isp-interface-segregation-principle/"
  },
  {
    "slug": "betonozas-30-liskov-es-a-haverok",
    "title": "Betonozás 3.0 – Liskov és a haverok",
    "publishedAt": "2016-07-05",
    "excerpt": "Kódolni pofonegyszerű. Legalábbis a facebook hirdetéseink alapján ma már mindenféle tudás nélkül bármit össze lehet kattintgatni és még lehet külsőre jól is néz ki. Ellenben ha minőségi munkáról van…",
    "oldPermalink": "/2016/07/05/betonozas-3-0-liskov-es-haverok/"
  },
  {
    "slug": "betonozas-2-resz-ocp",
    "title": "Betonozás 2. rész – OCP",
    "publishedAt": "2016-07-03",
    "excerpt": "Az előző cikkben elkezdtük tárgyalni a SOLID elveket. Az SRP-t ki is végeztük, így jöjjön a SOLID második pillére az OCP, azaz az open-closed principle, ami annyit tesz, hogy \"open for extension,…",
    "oldPermalink": "/2016/07/03/betonozas-2-resz-ocp/"
  },
  {
    "slug": "a-szilard-alapok",
    "title": "A szilárd alapok",
    "publishedAt": "2016-06-27",
    "excerpt": "Sok minden szóbakerült már a blogon, viszont egy igen fontos részt kihagytam, vagy csak érintőlegesen volt szó róla. Nem is biztos, hogy valaha direktben megkérdezik azt valakitől, hogy pontosan mit…",
    "oldPermalink": "/2016/06/27/a-szilard-alapok/"
  },
  {
    "slug": "tiszta-infrastruktura-1-resz-ha-faj-csinald-gyakrabban",
    "title": "Tiszta infrastruktúra, 1. rész — Ha fáj, csináld gyakrabban!",
    "publishedAt": "2016-06-27",
    "excerpt": "Ha üzemeltetésről beszélünk, jellemzően van néhány olyan dolog, amitől a rendszer gazdái hihetetlenül félnek. Ez lehet akár az, hogy egy felszentelt gép leállása, vagy a biztonsági mentések…",
    "oldPermalink": "/2016/06/27/tiszta-infrastruktura-1-resz-ha-faj-csinald-gyakrabban/"
  },
  {
    "slug": "nem-kivanatos-alkalmazasok-uzemeltetese-linuxon",
    "title": "„Nem kívánatos” alkalmazások üzemeltetése Linuxon",
    "publishedAt": "2016-06-20",
    "excerpt": "Időnként sajnos elkerülhetetlen, hogy olyan alkalmazásokat üzemeltessünk, amiket legszívesebben bottal sem piszkálnánk meg. Kinek a WordPress, kinek a Joomla, de szeretnénk minél jobban bezárni,…",
    "oldPermalink": "/2016/06/20/nem-kivanatos-alkalmazasok-uzemeltetese-linuxon/"
  },
  {
    "slug": "adatbazis-valtozasok-kezelese",
    "title": "Adatbázis változások kezelése",
    "publishedAt": "2016-06-14",
    "excerpt": "A tesztgépen még tökéletes volt, de az éles rendszeren hiányzik az adatbázis fele? Rémálom az élesítés? Beszélgessünk az adatbázis változások kezeléséről! A probléma A problémát szinte mindenki…",
    "oldPermalink": "/2016/06/14/adatbazis-valtozasok-kezelese/"
  },
  {
    "slug": "a-comment-on-how-we-learn-by-aino-vonge-corry",
    "title": "A Comment on How We Learn by Aino Vonge Corry",
    "publishedAt": "2016-06-12",
    "excerpt": "\\[youtube id=\"ozYipg-ox8Y\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Hol hibádzik az informatika oktatás? Hogyan legyünk jobb oktatók, hogyan tanuljunk hatékonyabban? Erről…",
    "oldPermalink": "/2016/06/12/a-comment-on-how-we-learn-by-aino-vonge-corry/"
  },
  {
    "slug": "programming-is-terrible-lessons-learned-from-a-life-wasted",
    "title": "Programming is terrible — Lessons learned from a life wasted",
    "publishedAt": "2016-06-08",
    "excerpt": "\\[youtube id=\"csyL9EC0S0c\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] A programozás borzalmas? Ez a rengeteg humorral és szarkazmussal teli előadás megmutatja, hogy hogyan…",
    "oldPermalink": "/2016/06/08/programming-is-terrible-lessons-learned-from-a-life-wasted/"
  },
  {
    "slug": "tiszta-kod-9-resz-helyezzuk-uzembe-a-blogot",
    "title": "Tiszta kód, 9. rész – Helyezzük üzembe a blogot!",
    "publishedAt": "2016-05-27",
    "excerpt": "Az előző részben megírtuk egy blog üzleti logikáját, teljesen figyelmen kívül hagyva a tényleges adatbázist vagy böngészőt. Most itt az ideje, hogy üzembe is helyezzük. Ez a cikk erősen épít a…",
    "oldPermalink": "/2016/05/27/tiszta-kod-9-resz-helyezzuk-uzembe-a-blogot/"
  },
  {
    "slug": "tiszta-kod-8-resz-egy-tiszta-kod-blog-kezdetei",
    "title": "Tiszta kód, 8. rész – Egy tiszta kód blog kezdetei",
    "publishedAt": "2016-05-17",
    "excerpt": "Az elmúlt hetekben rengeteget beszéltünk a különböző tiszta kódhoz kapcsolódó koncepciókról, elvekről és tervezési mintákról. Eljött az idő, hogy implementáljuk egy teljes projektet, elejétől a…",
    "oldPermalink": "/2016/05/17/tiszta-kod-8-resz-egy-tiszta-kod-blog-kezdetei/"
  },
  {
    "slug": "az-oktrojator-pattern-es-az-ioc-container",
    "title": "Az oktrojátor pattern és az IoC container",
    "publishedAt": "2016-05-16",
    "excerpt": "Az objektumorientált programnyelvekben értelemszerűen objektumokkal dolgozunk. Apróbb programok esetén, mikor nem használunk erre kitalált keretrendszert, az objektumpéldányaink menedzselése…",
    "oldPermalink": "/2016/05/16/shifu-es-az-inversion-control/"
  },
  {
    "slug": "tiszta-kod-7-resz-mi-a-fene-az-a-dependency-injection-container",
    "title": "Tiszta kód, 7. rész – Mi a fene az a Dependency Injection (Container)?",
    "publishedAt": "2016-05-09",
    "excerpt": "A S.O.L.I.D. elvek kapcsán beszéltünk arról, hogy nem jó, ha a moduljaink szorosan függenek egymástól. De mégis, hogy a fenébe működik ez a gyakorlatban? Figyelem! A cikk erősen épít a korábbi…",
    "oldPermalink": "/2016/05/09/tiszta-kod-7-resz-mi-a-fene-az-a-dependency-injection-container/"
  },
  {
    "slug": "repository-k-a-verziokovetesen-is-tul",
    "title": "Repository-k a verziókövetésen is túl",
    "publishedAt": "2016-05-08",
    "excerpt": "Amikor az ember kódolásba kezd, akkor gyakorta törekszik arra, hogy a kódja egyes részeit újra tudja hasznosítani, hogy azok modulárisak legyenek, át tudjuk vinni őket A projektből B projektbe,…",
    "oldPermalink": "/2016/05/08/repository-k-verziokovetesen-tul/"
  },
  {
    "slug": "the-future-of-programming-by-robert-c-martin",
    "title": "The Future of Programming by Robert C. Martin",
    "publishedAt": "2016-05-07",
    "excerpt": "\\[youtube id=\"9Xy3QC7yxJw\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Mi a programozás, mint szakma, jövője? Robert C. Martin (Uncle Bob) a számítástechnika kezdeti idejétől…",
    "oldPermalink": "/2016/05/07/the-future-of-programming-by-robert-c-martin/"
  },
  {
    "slug": "az-imagetragick-biztonsagi-hiba-margojara",
    "title": "Az ImageTragick biztonsági hiba margójára",
    "publishedAt": "2016-05-04",
    "excerpt": "Mostanára szinte biztos, hogy olvastad, hogy súlyos biztonsági hibákat találtak a népszerű ImageMagick nevű képfeldolgozó programkönyvtárban. Miután már a csapból is ez folyik, minket inkább az…",
    "oldPermalink": "/2016/05/04/az-imagetragick-biztonsagi-hiba-margojara/"
  },
  {
    "slug": "tiszta-kod-6-resz-beszelnunk-kell-az-mvc-rol",
    "title": "Tiszta kód, 6. rész – Beszélnünk kell az MVC-ről…",
    "publishedAt": "2016-05-02",
    "excerpt": "Beszédünk van. Múltkor azt állítottam, hogy az MVC-t szinte mindenki ismeri a szakmában. Az az igazság, hogy sokan azt hiszik, hogy ismerik. Mielőtt azonban belevágunk, nézzük is meg, hogy mi az az…",
    "oldPermalink": "/2016/05/02/tiszta-kod-6-resz-beszelnunk-kell-az-mvc-rol/"
  },
  {
    "slug": "diszitsuk-fel-a-wrappert",
    "title": "Díszítsük fel a wrappert!",
    "publishedAt": "2016-04-28",
    "excerpt": "A decorator pattern a struktúrális minták közé tartozik, és a célja roppant egyszerű: magába foglal egy másik osztályt és plusz funkcionalitással látja el azt, így az eredeti osztály metódusai…",
    "oldPermalink": "/2016/04/28/diszitsuk-fel-wrappert/"
  },
  {
    "slug": "tiszta-kod-5-resz-a-solid-alapelvek",
    "title": "Tiszta kód, 5. rész – A S.O.L.I.D. alapelvek",
    "publishedAt": "2016-04-26",
    "excerpt": "Ma a programozás terén szinte mindenki hallott már a Model-View-Controller kódszervezési elvről. Annak ellenére, hogy ez rengeteget segített abban, hogy a kód karbantarthatóbb legyen, a hosszú távú…",
    "oldPermalink": "/2016/04/26/tiszta-kod-5-resz-a-s-o-l-i-d-alapelvek/"
  },
  {
    "slug": "laravelre-at",
    "title": "Laravelre át",
    "publishedAt": "2016-04-24",
    "excerpt": "Az elkövetkező pár napban lehetnek az oldalon furcsaságok, mivel végre megszabadulunk a wordpress legtöbb kötöttségétől. Laravelre állt át az oldal, egy korábbi cikk alapján viszon az adminfelület…",
    "oldPermalink": "/2016/04/24/laravelre-at/"
  },
  {
    "slug": "tiszta-kod-4-resz-tdd-a-gyakorlatban",
    "title": "Tiszta kód, 4. rész – TDD a gyakorlatban",
    "publishedAt": "2016-04-19",
    "excerpt": "Itt az idő, most vagy soha: írjunk webáruházat tesztvezérelten! Ebben a cikkben azt nézzük meg, hogy hogyan is működik ez a TDD kérdés a gyakorlatban. Mivel ez a cikk némileg időigényes, előre…",
    "oldPermalink": "/2016/04/19/tiszta-kod-4-resz-tdd-a-gyakorlatban/"
  },
  {
    "slug": "eureka",
    "title": "Eureka!",
    "publishedAt": "2016-04-17",
    "excerpt": "Az elmúlt pár cikkben igyekeztem meglovagolni én is azt a hype-ot, ami a microservice architektúrával kapcsolatos, de eddig eléggé elméleti megközelítése volt a dolgoknak, így gondoltam most kicsit…",
    "oldPermalink": "/2016/04/17/eureka/"
  },
  {
    "slug": "tiszta-kod-2-resz-teszteljunk-tdd-vel",
    "title": "Tiszta kód, 2. rész: teszteljünk TDD-vel!",
    "publishedAt": "2016-04-07",
    "excerpt": "Az előző részben arról értekeztünk, hogy egyáltalán miért érdemes tesztelni. Ebben a részben bele is vágunk a kellős közepébe és megnézzük, hogy hogyan is zajlik egy egységteszt írása. Az…",
    "oldPermalink": "/2016/04/07/tiszta-kod-2-resz-teszteljunk-tdd-vel/"
  },
  {
    "slug": "facade-pattern",
    "title": "Facade pattern",
    "publishedAt": "2016-04-04",
    "excerpt": "Az elmúlt időszakban kissé eltávolodtunk a kódtól, pedig nem csak rendszerszinten lehet tekinteni itt a dolgokra, így most kicsit visszatérünk a hétköznapi kóder életbe, a tervezési minták világába.…",
    "oldPermalink": "/2016/04/04/facade-pattern/"
  },
  {
    "slug": "the-transformation-priority-premise-by-robert-c-martin",
    "title": "The Transformation Priority Premise by Robert C. Martin",
    "publishedAt": "2016-04-04",
    "excerpt": "\\[youtube id=\"B93QezwTQpI\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Ha már mostanában elkezdtünk a teszteléssel foglalkozni, hogyan működik a tesztvezérelt fejlesztés? Erről…",
    "oldPermalink": "/2016/04/04/the-transformation-priority-premise/"
  },
  {
    "slug": "a-microservice-hype",
    "title": "A microservice hype",
    "publishedAt": "2016-03-30",
    "excerpt": "Már egy jó ideje a csapból is az folyik (szerencsére már megunták), hogy a microservice architektúra mennyire cool és hogy a monolit alkalmazások fejlesztése buzis. A cikkben arról lesz szó, hogy is…",
    "oldPermalink": "/2016/03/30/a-microservice-hype/"
  },
  {
    "slug": "tiszta-kod-1-resz-teszteljek-vagy-ne-teszteljek",
    "title": "Tiszta kód, 1. rész: teszteljek vagy ne teszteljek?",
    "publishedAt": "2016-03-29",
    "excerpt": "Minden program köztudottan tartalmaz legalább egy hibát. Néha kezeljük, néha a szőnyeg alá söpörjük. Hogyan lehet automatizálni a tesztelést? Érdemes egyáltalán vele vesződni? Ez a cikk jelentős…",
    "oldPermalink": "/2016/03/29/tiszta-kod-1-resz-teszteljek-vagy-ne-teszteljek/"
  },
  {
    "slug": "agility-and-architecture-by-robert-c-martin",
    "title": "Agility and Architecture by Robert C. Martin",
    "publishedAt": "2016-03-25",
    "excerpt": "\\[youtube id=\"0oGpWmS0aYQ\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\] Hogyan fér meg egymás mellett az architekturális tervezés és az agile szemlélet? Van-e lehetőség…",
    "oldPermalink": "/2016/03/25/agility-and-architecture-by-robert-c-martin/"
  },
  {
    "slug": "hogyan-mukodik-az-internet-3-resz-az-icmp-a-udp-es-a-tcp",
    "title": "Hogyan működik az Internet, 3. rész: az ICMP, a UDP és a TCP",
    "publishedAt": "2016-03-24",
    "excerpt": "Az előző cikkeinkben azzal foglalkoztunk, hogy a csomagok hogyan találnak a megfelelő helyre az Interneten. Most végre elérkezett az idő, hogy megnézzük mire is lesz ez jó. Ezúttal három, IP-re épülő…",
    "oldPermalink": "/2016/03/24/hogyan-mukodik-az-internet-3-resz-az-icmp-a-udp-es-a-tcp/"
  },
  {
    "slug": "refactoring-a-javabol",
    "title": "Refactoring a javából",
    "publishedAt": "2016-03-24",
    "excerpt": "Elképesztő módon elmaradtam az írásokkal, amire semmilyen (még az ivás se) lehet mentségemre. Ezért most ha tudom, akkor megpróbálom pótolni, de már inkább nem is ígérek semmit, mert eddig nem úgy…",
    "oldPermalink": "/2016/03/24/refactoring-a-javabol/"
  },
  {
    "slug": "steal-everything-kill-everyone-cause-total-financial-ruin-by-jayson-e-street",
    "title": "Steal Everything, Kill Everyone, Cause Total Financial Ruin! by Jayson E. Street",
    "publishedAt": "2016-03-18",
    "excerpt": "\\[youtube id=\"JsVtHqICeKE\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/03/18/steal-everything-kill-everyone-cause-total-financial-ruin-by-jayson-e-street/"
  },
  {
    "slug": "professional-software-development-by-robert-c-martin",
    "title": "Professional Software Development by Robert C. Martin",
    "publishedAt": "2016-03-17",
    "excerpt": "\\[youtube id=\"zwtg7lIMUaQ\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/03/17/professional-software-development-by-robert-c-martin/"
  },
  {
    "slug": "low-level-debugolas-2-resz-halozati-eszkozok",
    "title": "Low level debugolás, 2. rész: hálózati eszközök",
    "publishedAt": "2016-03-16",
    "excerpt": "A sorozat első részében megnéztük, hogy hogyan lehet egy folyamat rendszerhívásait nyomon követni. Sokszor ez azonban körülményes, ha csak a hálózati forgalomra vagyunk kíváncsiak. Ilyenkor jól jön,…",
    "oldPermalink": "/2016/03/16/low-level-debugolas-2-resz-halozati-eszkozok/"
  },
  {
    "slug": "core-design-principles-for-software-developers-by-venkat-subramaniam",
    "title": "Core Design Principles for Software Developers by Venkat Subramaniam",
    "publishedAt": "2016-03-14",
    "excerpt": "\\[youtube id=\"llGgO74uXMI\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/03/14/core-design-principles-for-software-developers-by-venkat-subramaniam/"
  },
  {
    "slug": "hogyan-mukodik-az-internet-2-resz-az-internet-protokoll",
    "title": "Hogyan működik az Internet, 2. rész: az Internet Protokoll",
    "publishedAt": "2016-03-08",
    "excerpt": "A cikksorozatunk előző részében azzal foglalkoztunk, hogy hogyan kommunikálnak az eszközök a helyi hálózatban. Ebben a részben azt nézzük meg hogyan tudunk kitörni a helyi hálózatból, és kijutni a…",
    "oldPermalink": "/2016/03/08/hogyan-mukodik-az-internet-2-resz-az-internet-protokoll/"
  },
  {
    "slug": "115-batshit-stupid-things-you-can-put-on-the-internet-by-dan-tentler",
    "title": "115 batshit stupid things you can put on the internet by Dan Tentler",
    "publishedAt": "2016-03-07",
    "excerpt": "\\[youtube id=\"hMtu7vV\\HmY\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/03/07/115-batshit-stupid-things-you-can-put-on-the-internet-by-dan-tentler/"
  },
  {
    "slug": "5-ok-hogy-miert-felejtsd-el-az-ftp-t",
    "title": "5 ok, hogy miért felejtsd el az FTP-t",
    "publishedAt": "2016-02-29",
    "excerpt": "Az FTP az internet kezdeti napjai óta létezik, és elterjedt módja a fájlok átvitelének. Mindazonáltal, mint megannyi régi protokoll, rengeteg problémával küzd. Sok más protokollal ellentétben sajnos…",
    "oldPermalink": "/2016/02/29/5-ok-hogy-miert-felejtsd-el-az-ftp-t/"
  },
  {
    "slug": "az-automatizalt-rendszergazda",
    "title": "Az automatizált rendszer(gazda)",
    "publishedAt": "2016-02-29",
    "excerpt": "Kilencvenes évek. Valahol egy sötét szobában egy magányos alak ül egy CRT monitor előtt. Egyszer csak nyílik egy ajtó, világosság látszik, és félve lép be egy irodai alkalmazott, halkan megköszörüli…",
    "oldPermalink": "/2016/02/29/az-automatizalt-rendszergazda/"
  },
  {
    "slug": "dont-look-for-things-by-misko-hevery",
    "title": "Don’t Look For Things! by Misko Hevery",
    "publishedAt": "2016-02-29",
    "excerpt": "\\[youtube id=\"RlfLCWKxHJ0\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/02/29/dont-look-for-things-by-misko-hevery/"
  },
  {
    "slug": "hogyan-mukodik-az-internet-1-resz-az-ethernet",
    "title": "Hogyan működik az Internet, 1. rész: az Ethernet",
    "publishedAt": "2016-02-29",
    "excerpt": "Sokszor a hibakeresésnél fontos lenne, ám nem tudjuk: hogyan is működnek az alapok. Éppen ezért ebben a cikksorozatban az Internetet szedjük szét, kezdve a legalsó szoftveres réteggel: hogyan működik…",
    "oldPermalink": "/2016/02/29/hogyan-mukodik-az-internet-1-resz-az-ethernet/"
  },
  {
    "slug": "how-to-design-a-good-api-and-why-it-matters",
    "title": "How To Design A Good API and Why it Matters",
    "publishedAt": "2016-02-29",
    "excerpt": "\\[youtube id=\"aAb7hSCtvGw\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/02/29/how-to-design-a-good-api/"
  },
  {
    "slug": "idokezeles-a-programozasban",
    "title": "Időkezelés a programozásban",
    "publishedAt": "2016-02-29",
    "excerpt": "Talán nincs még egy olyan téma a fejlesztés terén, ahol annyi hibát és téves értelmezést látok, mint az időkezelésben. Tény, hogy valóban nem egyszerű kérdés, rengeteg mindennel kell foglalkoznunk,…",
    "oldPermalink": "/2016/02/29/idokezeles-a-programozasban/"
  },
  {
    "slug": "low-level-debugolas-1-resz-strace",
    "title": "Low level debugolás, 1. rész: strace",
    "publishedAt": "2016-02-29",
    "excerpt": "Teljesen mindegy, hogy fejlesztünk vagy üzemeltetünk, időnként előfordul, hogy olyan szoftvert kell életre lehelnünk, amely kódminősége finoman szólva hagy némi kívánni valót maga után. Ilyen esetben…",
    "oldPermalink": "/2016/02/29/low-level-debugolas-1-resz-strace/"
  },
  {
    "slug": "the-silver-bullet-syndrome-by-hadi-hariri",
    "title": "The Silver Bullet Syndrome by Hadi Hariri",
    "publishedAt": "2016-02-29",
    "excerpt": "\\[youtube id=\"3wyd6J3yjcs\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/02/29/the-silver-bullet-syndrome-by-hadi-hariri/"
  },
  {
    "slug": "transzparencia-a-fizetesekben",
    "title": "Transzparencia a fizetésekben?",
    "publishedAt": "2016-02-29",
    "excerpt": "Az IT közösségben sokszor felmerül egy-egy álláshirdetés kapcsán az az aggály, hogy a hirdető cég nem adja meg a várható fizetést, vagy fizetési sávot, a munkavállalói fizetéseket pedig szokás üzleti…",
    "oldPermalink": "/2016/02/29/transzparencia-a-fizetesekben-interju/"
  },
  {
    "slug": "unit-testing-by-misko-hevery",
    "title": "Unit Testing by Misko Hevery",
    "publishedAt": "2016-02-29",
    "excerpt": "\\[youtube id=\"wEhu57pih5w\" width=\"1100\" height=\"618\" autoplay=\"yes\" api\\params=\"\" class=\"\"\\]",
    "oldPermalink": "/2016/02/29/unit-testing-by-misko-hevery/"
  },
  {
    "slug": "partizankodas-3-tele-a-puttonyt",
    "title": "Partizánkodás 3 – Tele a puttonyt!",
    "publishedAt": "2016-02-07",
    "excerpt": "Az előző részben elkezdtük csinálni a saját kis composer package-ünket, ami egyelőre még elég szegényes funkcionalitással bír. Most nem ártana telepakolni azokkal a bizonyos tutiságokkal és ha…",
    "oldPermalink": "/2016/02/07/laravel-5-tele-a-puttonyt/"
  },
  {
    "slug": "helyszini-teszt-2016-februar",
    "title": "Helyszíni teszt –  2016 Február",
    "publishedAt": "2016-01-31",
    "excerpt": "Ismét kivetítő elé engednek! Ezúttal az előadás témája : Tesztelés laravel 5 alatt. Akárki akármit mond, a fejlesztők hibáznak. Minél komplexebb egy feladat, annál több apróság csúszhat be. Mindent…",
    "oldPermalink": "/2016/01/31/helyszini-teszteles-2016-februar/"
  },
  {
    "slug": "partizankodas-2-csomagolastechnika",
    "title": "Partizánkodás 2 – Csomagolástechnika",
    "publishedAt": "2016-01-17",
    "excerpt": "Amikor az ember fejlesztésbe kezd, és eljut arra a pontra, hogy egy kódrészletet átmásol A helyről B-be, akkor a józan ész azt diktálja, hogy bizony ezt lehetne szebben is csinálni. Azt a részt, amit…",
    "oldPermalink": "/2016/01/17/partizankodas-2-csomagolastechnika/"
  },
  {
    "slug": "partizankodjunk-a-laravel-5-el",
    "title": "Partizánkodjunk a laravel 5-el!",
    "publishedAt": "2016-01-11",
    "excerpt": "Ismert a mondás, miszerint amit automatizálni lehet, azt automatizálni is kell. Nincs ez máshogy a programozásban sem, sőt itt kellene kiélni mindezt. Bizonyára mindenki szeret kódolni, jó érzés…",
    "oldPermalink": "/2016/01/11/partizankodjunk-a-laravel-5-el/"
  },
  {
    "slug": "uj-ev-uj-temakor",
    "title": "Új év, új témakör",
    "publishedAt": "2016-01-03",
    "excerpt": "A 2015-ös év végén kicsit megnyomtam a Javascript vonalat, ami már igencsak kellett, viszont a szervezetem is megérezte, ugyanis eléggé lebetegedtem tőle. Így a következő napokban (vagy hetekben,…",
    "oldPermalink": "/2016/01/03/uj-ev-uj-temakor/"
  },
  {
    "slug": "2015-review",
    "title": "2015 review",
    "publishedAt": "2015-12-31",
    "excerpt": "Most, hogy több, mint egy év eltelt az első bejegyzés óta, épp itt az ideje, hogy meginterjuholjalak benneteket: - Jó irányba halad-e az oldal? - A tartalom nem lett unalmas? Ugyanis fő célom az…",
    "oldPermalink": "/2015/12/31/2015-review/"
  },
  {
    "slug": "javascript-pakk-3-kinek-kell-a-js",
    "title": "Javascript pakk 3 – Kinek kell a JS?",
    "publishedAt": "2015-12-30",
    "excerpt": "Azt már az előző cikkemben is említettem, hogy bizony frontendesnek lenni nem <delcsak a húszéveseké</del fenékig tejfel. A böngészők, habár okosak, mindent nem tudnak helyettünk, főleg azért, mert a…",
    "oldPermalink": "/2015/12/30/javascript-pakk-3-kinek-kell-a-js/"
  },
  {
    "slug": "javaspricc-pakk-2-babel",
    "title": "Javaspricc pakk 2 – Babel",
    "publishedAt": "2015-12-26",
    "excerpt": "Az előző cikkemben szó volt az ECMAScript 6 újításairól. Itt kitértem arra is, hogy azért nem szabad rögtön fejest ugrani a dologba, lévén a böngészők támogatottsága elég vegyes. Viszont az előző…",
    "oldPermalink": "/2015/12/26/javaspricc-pakk-2-babel/"
  },
  {
    "slug": "javascript-pakk-no-1-ecmascript-6",
    "title": "Javascript pakk No. 1 – ECMAScript 6",
    "publishedAt": "2015-12-24",
    "excerpt": "A frontend fejlesztők élete nem csak játék és mese. Nem elég hogy a javascript prototype object modelje sokakban a hányingerre kisértetiesen emlékeztető érzéseket kelt, mindezt megfejelik aszinkron…",
    "oldPermalink": "/2015/12/24/javascript-pakk-no-1-ecmascript-6/"
  },
  {
    "slug": "back-up-me-baby-one-more-time",
    "title": "Back (up) me baby one more time!",
    "publishedAt": "2015-12-19",
    "excerpt": "Akárki akármit mondd, biztonsági mentéseket csinálni fontos. Előző cikkemben átvettünk pár dolgot a mentések mibenlétét illetően és elindultunk a legegyszerűbb módszerektől, amit most folytatnánk az…",
    "oldPermalink": "/2015/12/19/back-up-me-baby-one-more-time/"
  },
  {
    "slug": "scooter-back-it-up",
    "title": "Scooter – Back it up",
    "publishedAt": "2015-12-17",
    "excerpt": "A biztonsági mentés és visszaállítás létfontosságú<del aki azt mondja, hogy nem, az fütyül és/vagy hazudik</del. A legtöbben saját kárukon tanulják meg mindezt, mikor is végleg oda lesz valamennyi…",
    "oldPermalink": "/2015/12/17/scooter-back-it-up/"
  },
  {
    "slug": "backup-ftw",
    "title": "Backup FTW",
    "publishedAt": "2015-12-07",
    "excerpt": "Akik rendszeresen látogatják az oldalt, azoknak bizonyára feltűnt ez a kis hétvégi leállás és káosz. Gondok adódtak az adatbázissal, de egy jól szituált backup mindent megoldott, így a következő…",
    "oldPermalink": "/2015/12/07/backup-ftw/"
  },
  {
    "slug": "eloben-jelentkezunk-a-helyszinrol",
    "title": "Élőben jelentkezünk a helyszínről!",
    "publishedAt": "2015-11-10",
    "excerpt": "Aki Budapest belvárosában tartózkodik november 25.-én és nem tud jobb alternatívát találni arra mivel is üsse el az időt este 7-től, annak felajánlanék egy alternatívát: \\[box type=\"shadow\" \\]…",
    "oldPermalink": "/2015/11/10/eloben-jelentkezunk-a-helyszinrol/"
  },
  {
    "slug": "laravel-50-request-es-response",
    "title": "Laravel 5.0 – Request és Response",
    "publishedAt": "2015-11-01",
    "excerpt": "Az előző részekben átvettük hogy is épül fel egy átlagos laravel alkalmazás könyvtárstruktúrája, hogy lehet route-okat definiálni, valamint szóba kerültek a controllerek és middleware-ek. Mivel…",
    "oldPermalink": "/2015/11/01/laravel-5-0-request-es-response/"
  },
  {
    "slug": "dokkolnam-dokkolnam",
    "title": "Dokkolnám, dokkolnám!",
    "publishedAt": "2015-10-25",
    "excerpt": "<figure aria-describedby=\"caption-attachment-782\" class=\"wp-caption aligncenter\" id=\"attachment782\" style=\"width: 515px\"<figcaption class=\"wp-caption-text\" id=\"caption-attachment-782\"A konténerek…",
    "oldPermalink": "/2015/10/25/dokkolnam-dokkolnam/"
  },
  {
    "slug": "martin-papa-szinrelep-az-adataink",
    "title": "Martin papa színrelép – Az adataink",
    "publishedAt": "2015-10-13",
    "excerpt": "Az bizonyára köztudott, hogy manapság már nem weboldalakat, hanem webalkalmazásokat készítünk, azok mérete és komplexitása miatt. Ezzel a mérettel és komplexitással szinte egyenes arányban egyre…",
    "oldPermalink": "/2015/10/13/martin-papa-szinrelep-az-adataink/"
  },
  {
    "slug": "eredmenyhirdetes",
    "title": "Eredményhirdetés",
    "publishedAt": "2015-09-25",
    "excerpt": "Egyéb platformokon megtudakoltam, hogy mi is legyen annak a bizonyos előadásnak a témája és az alábbi eredmények születtek 1. Általános OO programozás (pl. design patternek, stb.) - 19 2. Laravel -…",
    "oldPermalink": "/2015/09/25/eredmenyhirdetes/"
  },
  {
    "slug": "strategy-pattern-az-objektumok-lazadasa",
    "title": "Strategy pattern, az objektumok lázadása",
    "publishedAt": "2015-09-03",
    "excerpt": "Minden fejlesztő életében vannak nehéz napok, mikor <deliOS push notificationt akar megvalósítani C-al</del úgy érzi, hogy az általa kreált objektum jónak jó, de mi lenne ha több mindenre lenne jó,…",
    "oldPermalink": "/2015/09/03/strategy-pattern-az-objektumok-lazadasa/"
  },
  {
    "slug": "command-pattern-es-a-penzugyszamvitel",
    "title": "Command Pattern és a pénzügy/számvitel",
    "publishedAt": "2015-08-30",
    "excerpt": "Most, hogy a mai napi <delorbitális szívás</del programozási kihívásokon túlestem, ideje megosztani az infót<del valami másról, hogy mások is szívjanak annyit, mint én</del. <figure…",
    "oldPermalink": "/2015/08/30/command-pattern-es-a-penzugyszamvitel/"
  },
  {
    "slug": "controller-es-middleware-a-ket-jobarat",
    "title": "Controller és middleware a két jóbarát",
    "publishedAt": "2015-08-25",
    "excerpt": "Most, hogy a routingot tisztába tettük, nézzünk egy kicsit bele abba, hogy azokat a route-okat, amiket belőttünk miféle controllerekbe tudjuk belevezetni? Hiszen nem gondolhatjuk komolyan, hogy a…",
    "oldPermalink": "/2015/08/25/controller-es-middleware-a-ket-jobarat/"
  },
  {
    "slug": "martin-papa-strikes-back-domain-logic-2",
    "title": "Martin papa strikes back – Domain Logic 2.",
    "publishedAt": "2015-08-24",
    "excerpt": "Az előző cikk elég kuszára sikerült, úgyhogy most muszáj lesz kárpótolni benneteket. A folytatás témája a Table Module és a Service Layer lesz, amikkel együtt kellő alapot hoztunk létre, hogy…",
    "oldPermalink": "/2015/08/24/martin-papa-strikes-back-domain-logic-2/"
  },
  {
    "slug": "martin-papa-kozbelep-domain-logic",
    "title": "Martin papa közbelép – Domain Logic",
    "publishedAt": "2015-08-22",
    "excerpt": "Sok helyen és cikkben lehet olvasni a Domain, Domain Logic szót, azonban a legtöbb helyen nincs leírva, hogy ez pontosan mi? A Domain Logic írja le azokat a funkcionális algoritmusokat vagy épp…",
    "oldPermalink": "/2015/08/22/martin-papa-kozbelep-domain-logic/"
  },
  {
    "slug": "gittegylet-4-jegyeket-berleteket",
    "title": "Gittegylet 4 – Jegyeket, bérleteket",
    "publishedAt": "2015-08-18",
    "excerpt": "A verziókövetésnek bármelyikről is beszéljünk, van egy bizonyos workflow-ja, amit ha nem is teljesen, de egyes részeit bizonyára megismertük már a használat közben. A Git, más rendszerekhez hasonlóan…",
    "oldPermalink": "/2015/08/18/gittegylet-4-jegyeket-berleteket/"
  },
  {
    "slug": "nyelvtani-alapok-lara-vallaravel",
    "title": "Nyelvtani alapok.. Lara-val..Laravel",
    "publishedAt": "2015-08-17",
    "excerpt": "Igen, eljutottunk ide is, mainstream keretrendszerekről is írok. Múltkor felmerült a kérdés a Zendes cikkem kapcsán, hogy miért pont Zend? Nos, habár sem magyar, sem világ viszonylatban nem egy…",
    "oldPermalink": "/2015/08/17/nyelvtani-alapok-lara-val-laravel/"
  },
  {
    "slug": "zendules-1-resz-skeleton-application",
    "title": "ZENDülés 1. rész – Skeleton application",
    "publishedAt": "2015-08-02",
    "excerpt": "Amikor az ember belekezd a webfejlesztésbe és már némileg túllépett a \"Hello world!\" szinten, akkor ahogy sorra ontja ki magából a webalkalmazásokat, amiket autentikusan nulláról húz fel, akkor előbb…",
    "oldPermalink": "/2015/08/02/zendules-1-resz-skeleton-application/"
  },
  {
    "slug": "termiterator-2",
    "title": "Termi(ter)ator 2",
    "publishedAt": "2015-07-06",
    "excerpt": "A mai téma egy roppant egyszerű tervezési minta lesz, amire - ahogy a későbbiekben kiderül - a programnyelveink többségében már példát is találunk. Ha valaha volt már dolgod valamilyen adatbázissal…",
    "oldPermalink": "/2015/07/06/termiterator-2/"
  },
  {
    "slug": "observer-pattern-es-a-robotics-facility",
    "title": "Observer pattern és a Robotics Facility",
    "publishedAt": "2015-06-16",
    "excerpt": "<figure aria-describedby=\"caption-attachment-537\" class=\"wp-caption aligncenter\" id=\"attachment537\" style=\"width: 724px\"<figcaption class=\"wp-caption-text\" id=\"caption-attachment-537\"Protoss observer…",
    "oldPermalink": "/2015/06/16/observer-pattern-es-a-robotics-facility/"
  },
  {
    "slug": "javascript-oop",
    "title": "Javascript O(O)P",
    "publishedAt": "2015-05-17",
    "excerpt": "A webfejlesztésnek, akár akarjuk, akár nem, bizony szerves részét képezi a frontend, így az életutunkbizony keresztezni fogja némi javascript, kivéve, ha dedikáltan backendesek vagyunk. Viszont amit…",
    "oldPermalink": "/2015/05/17/javascript-oop/"
  },
  {
    "slug": "husveti-kulonkiadas-amqp",
    "title": "Húsvéti különkiadás – AMQP",
    "publishedAt": "2015-05-01",
    "excerpt": "Mivel vége lett az elmúlt hetek epikus hajtásának, ezért most fogom elkezdeni bepótolni a finomságokat, úgyhogy a napokban visszatér a már megszokott 2-3 poszt/hét tempó. Ha már az egyik korábbi…",
    "oldPermalink": "/2015/05/01/husveti-kulonkiadas-amqp/"
  },
  {
    "slug": "a-gyarba-vissza-e-servicelocator",
    "title": "A gyárba vissza E! – ServiceLocator",
    "publishedAt": "2015-04-01",
    "excerpt": "Az alábbi cikk főképp azoknak lehet hasznos, akik: <figure aria-describedby=\"caption-attachment-526\" class=\"wp-caption aligncenter\" id=\"attachment526\" style=\"width: 640px\"<figcaption…",
    "oldPermalink": "/2015/04/01/a-gyarba-vissza-e-servicelocator/"
  },
  {
    "slug": "git-3-under-the-hood",
    "title": "Git 3 – Under the hood",
    "publishedAt": "2015-03-27",
    "excerpt": "Szedd össze, amid van... Aki ismeri a fenti 30Y számot, annak se lesz világos, hogy miről lesz most szó, úgyhogy ne is foglalkozzunk vele, hanem rántsuk le a leplet a hőn áhított git merge-ről! Az…",
    "oldPermalink": "/2015/03/27/git-3-under-the-hood/"
  },
  {
    "slug": "gittegylet-2-a-karosszerialakatos-visszavag",
    "title": "Gittegylet 2 – A karosszérialakatos visszavág",
    "publishedAt": "2015-03-23",
    "excerpt": "Az előző részbenegylet\") kitárgyaltunk egy pár parancsot, amik a git alapvető használatához szükségesek (igen, a pull kimaradt, ezt mindjárt orvosoljuk) , ebben a részben kicsit mélyebben belemegyünk…",
    "oldPermalink": "/2015/03/23/gittegylet-2-a-karosszerialakatos-visszavag/"
  },
  {
    "slug": "vagrant-es-rio-de-janeiro",
    "title": "Vagrant és Rio de Janeiro",
    "publishedAt": "2015-03-19",
    "excerpt": "A webfejlesztők életének sok-sok fázisa van. Legtöbbünk úgy kezdi, hogy valahol látja/hallja, megtetszik neki, utána tutorialokat olvas, utánajár, majd felpatkol otthon egy AMP stack-et és azon…",
    "oldPermalink": "/2015/03/19/vagrant-es-rio-de-janeiro/"
  },
  {
    "slug": "composer-a-php-fejlesztok-kedvenc-zeneszerzoje",
    "title": "Composer – A PHP fejlesztők kedvenc zeneszerzője",
    "publishedAt": "2015-03-12",
    "excerpt": "Van egy mondás, miszerint az okos/rutinos programozó nem fogja újra és újra feltalálni a kereket, hiszen az teljesen felesleges időpocséklás lenne, hanem leakaszt egy már meglévő library-t a polcról…",
    "oldPermalink": "/2015/03/12/composer-a-php-fejlesztok-kedvenc-zeneszerzoje/"
  },
  {
    "slug": "memcached-serve-it-or-do-not-serve-it-but-serve-it-fast",
    "title": "Memcached – Serve it or do not serve it, but serve it fast",
    "publishedAt": "2015-03-12",
    "excerpt": "Amikor az ember rákeres a PHP és cache szavakra, óhatatlan, hogy rábukkanjon az apc/memcache/memcached szócskára (kéretik nem összetéveszteni). Mi most ez utóbbit fogjuk a műtőasztalra emelni, a…",
    "oldPermalink": "/2015/03/12/memcached-serve-it-or-do-not-serve-it-but-serve-it-fast/"
  },
  {
    "slug": "kincs-ami-nincs-2-resz",
    "title": "Kincs, ami nincs – 2. rész",
    "publishedAt": "2015-03-06",
    "excerpt": "Az előző cikkemben volt szó arról, hogy mi is alapjában véve a MongoDb és milyen flexibilitást nyújt, ellenben arra nem tértem ki, hogy is tudjuk ezt fellőni. Aki türelmetlen és nem akar vesződni a…",
    "oldPermalink": "/2015/03/06/kincs-ami-nincs-2-resz/"
  },
  {
    "slug": "anulu-elete-pongo-mongodb-szigeten",
    "title": "Anulu élete Pongo-MongoDB szigetén",
    "publishedAt": "2015-03-03",
    "excerpt": "Aki <dellátta már a Kincs, ami nincs című szuperprodukciót</del találkozott már a MongoDB szócskával, demindeddig halvány gőze se volt arról, hogy ez pontosan mi is és mire való, azt leszámítva, hogy…",
    "oldPermalink": "/2015/03/03/anulu-elete-pongo-mongodb-szigeten/"
  },
  {
    "slug": "long-polling-sse-websocket-mmx-es-mas-szep-szakszavak",
    "title": "Long polling, SSE, Websocket, MMX és más szép szakszavak",
    "publishedAt": "2015-02-28",
    "excerpt": "A betyárnagy érdeklődésre hallgatok és a mostani témánk az lesz, hogy mi is az a polling, long polling és cikkemben kitérek a kliens-szerver kommunikáció egyéb módjaira és azok megvalósítására.…",
    "oldPermalink": "/2015/02/28/long-polling-sse-websocket-mmx-es-mas-szep-szakszavak/"
  },
  {
    "slug": "de-jegyezd-meg-jol-mig-a-fold-kerek-mindig-lesznek-nevterek",
    "title": "De jegyezd meg jól, míg a Föld kerek, mindig lesznek névterek!",
    "publishedAt": "2015-02-24",
    "excerpt": "Tudom, hogy tartozom még mindenféle cikkel, ezért rangsorolnom kell őket, aszerint, hogy épp mennyire nagy a baj az adott területen vagy épp mennyire sürgető lenne megismerni olyan dolgokat, amik így…",
    "oldPermalink": "/2015/02/24/de-jegyezd-meg-jol-mig-a-fold-kerek-mindig-lesznek-nevterek/"
  },
  {
    "slug": "a-git-tegylet",
    "title": "A git (t)egylet",
    "publishedAt": "2015-02-22",
    "excerpt": "Aki sokat nézegeti a programozói álláshirdetéseket, annak bizonyára ismerős lehet a verziókövető rendszer kifejezés, ami vagy a követelmények vagy az \"előnyt jelent\" kategóriában, de igen gyakran…",
    "oldPermalink": "/2015/02/22/a-git-tegylet/"
  },
  {
    "slug": "a-proxy-pattern-szerepe-az-okori-romaban",
    "title": "A Proxy Pattern szerepe az ókori rómában",
    "publishedAt": "2015-02-19",
    "excerpt": "A mai témánk egy igen egyszerű, ám hasznos tervezési minta lesz, mégpedig a proxy. A név sokaknak ismerős lehet, akik próbáltak már céges netről betyárkodni és a dolog nem akart sehogy se összejönni…",
    "oldPermalink": "/2015/02/19/a-proxy-pattern-szerepe-az-okori-romaban/"
  },
  {
    "slug": "builder-pattern-es-a-7-hardveres",
    "title": "Builder Pattern és a 7 hardveres",
    "publishedAt": "2015-02-16",
    "excerpt": "Mai cikkemben a Builder Pattern kerül terítékre, hogy egy újabbat leleplezzünk a létrehozási minták közül. Mielőtt azonban beleugranánk abba, hogy mit is csinálunk ezen mintában, előtte valamit át…",
    "oldPermalink": "/2015/02/16/builder-pattern-es-7-hardveres/"
  },
  {
    "slug": "keresre-sessionmanager",
    "title": "Kérésre: SessionManager",
    "publishedAt": "2015-02-14",
    "excerpt": "Az egyik előző cikkemben felmerült a kérdés, hogy mégis hogy néz ki egy ilyen sessionkezelés a gyakorlatban és mivel ez egy hozzászólás keretein belül nem kivitelezhető, úgy gondoltam akkor egy…",
    "oldPermalink": "/2015/02/14/keresre-sessionmanager/"
  },
  {
    "slug": "its-a-kind-of-magic",
    "title": "It’s a kind of __magic()!",
    "publishedAt": "2015-02-13",
    "excerpt": "A PHP nyelvben objektumainknak akadnak olyan metódusai, melyeket nem tudunk direkt módon hivatkozással elérni, hanem egy bizonyos működéshez kötődnek. Ezeket a függvényeket mágikus metódusoknak…",
    "oldPermalink": "/2015/02/13/its-a-kind-of-__magic/"
  },
  {
    "slug": "az-md5-art-az-egeszsegnek",
    "title": "Az MD5 árt az egészségnek!",
    "publishedAt": "2015-02-10",
    "excerpt": "Mázlim volt és ezen a szerveren se volt letiltva az eval függvény (ahogy sok más sem 3:)), így most szabadon garázdálkodhatok rajta. Hozzá is adtam rögtön egy felhasználót magamnak c999-en át Mai…",
    "oldPermalink": "/2015/02/10/az-md5-art-az-egeszsegnek/"
  },
  {
    "slug": "cache-avagy-a-dugikeszletek",
    "title": "Cache, avagy a dugikészletek.",
    "publishedAt": "2015-02-05",
    "excerpt": "Ahhoz, hogy igényesen elmélyüljünk a gyorsítótárazás mikéntjében, első körben tisztáznunk kellene azt, hogy pontosan mit is értünk cache alatt. Gyorsítótárazásnak nevezzük azt az átmeneti információ…",
    "oldPermalink": "/2015/02/05/cache-avagy-dugikeszletek/"
  },
  {
    "slug": "keresooptimalizalas-maskepp-opcache",
    "title": "Keresőoptimalizálás másképp – OPcache",
    "publishedAt": "2015-02-01",
    "excerpt": "Aki valaha elmélyült a keresőoptimalizálásban az tudja, hogy rengeteg buktatója van a dolognak és a kedves Google valamikor úgy döntött, hogy ezt az optimalizálási folyamatot egy újabb tényezővel…",
    "oldPermalink": "/2015/02/01/keresooptimalizalas-maskepp-opcache/"
  },
  {
    "slug": "onvedelmi-gyakorlatok-csrf-es-session-hijacking",
    "title": "Önvédelmi gyakorlatok – CSRF és Session hijacking",
    "publishedAt": "2015-01-30",
    "excerpt": "Az előző részben végigvettünk pár támadási formát és az ellenük való védekezés lehetőségét. Ebben a részben a CSRF-el, a cross site request forgery-vel és a session hijackingel fogunk foglalkozni. A…",
    "oldPermalink": "/2015/01/30/onvedelmi-gyakorlatok-csrf-es-session-hijacking/"
  },
  {
    "slug": "tervezesi-mintak-adapter-pattern",
    "title": "Tervezési minták – Adapter pattern",
    "publishedAt": "2015-01-29",
    "excerpt": "Kicsit megtörjük most a sort és a létrehozási minták helyett (amik közül a jómunkásember Builder következne) egy másik csoportból fogunk elővenni egyet, mégpedig a struktúrális minták közül, az…",
    "oldPermalink": "/2015/01/29/tervezesi-mintak-adapter-pattern/"
  },
  {
    "slug": "prototype-pattern-ii-a-klonok-tamadasa",
    "title": "Prototype Pattern II – A klónok támadása",
    "publishedAt": "2015-01-26",
    "excerpt": "A prototype pattern olyan esetekben lehet segítségünkre, mikor adott objektumból sok másolatot készítünk és mindeközben a teljesítményt tartjuk szem előtt. A minta a létrehozási minták közé tartozik…",
    "oldPermalink": "/2015/01/26/prototype-pattern-ii-klonok-tamadasa/"
  },
  {
    "slug": "factory-pattern-a-munkanak-vege-kijossz-a",
    "title": "Factory Pattern – A munkának vége, kijössz a…",
    "publishedAt": "2015-01-24",
    "excerpt": "A tervezési mintákkal foglalkozó sorozatunk második részéhez értünk, ahol az objektumainkat bizony egy gyártósor fogja ontani magából. A factory pattern az egyik leggyakrabban használt minták közé…",
    "oldPermalink": "/2015/01/24/factory-pattern-munkanak-vege-kijossz/"
  },
  {
    "slug": "tervezesi-mintak-singleton-es-a-het-torpe",
    "title": "Tervezési minták – Singleton és a hét törpe",
    "publishedAt": "2015-01-24",
    "excerpt": "Elérkeztünk hát a tervezési minták taglalásához, így hát vegyük is át pontosan mit is értünk ez alatt. Az informatikában programtervezési mintáknak (angolul Software Design Patterns) nevezik a…",
    "oldPermalink": "/2015/01/24/tervezesi-mintak-singleton-es-het-torpe/"
  },
  {
    "slug": "onvedelmi-gyakorlatok-1-resz",
    "title": "Önvédelmi gyakorlatok – 1. rész",
    "publishedAt": "2015-01-22",
    "excerpt": "Aki már helyezett ki kódot éles környezetbe (és volt némi felelősségérzete persze :D) abban bizonyára felmerült többször is, hogy \"vajon mindent megtettem a szerverem biztonsága érdekében?\". Nos a…",
    "oldPermalink": "/2015/01/22/onvedelmi-gyakorlatok-1-resz/"
  },
  {
    "slug": "oops-i-did-it-again-avagy-dependency-injection-praktikak",
    "title": "OOP’s I DI’d it again!, avagy dependency injection praktikák",
    "publishedAt": "2015-01-21",
    "excerpt": "Mielőtt bármibe is belekezdenénk, először is tisztáznunk kell mi is az a dependency injection ( függőség injektálás, magyarul elég morbidul hangzik). Az objektumorientált programozásban az…",
    "oldPermalink": "/2015/01/21/oops-avagy-dependency-injection-praktikak/"
  },
  {
    "slug": "php-oop-absztrakt-osztalyok-es-interfeszek",
    "title": "PHP OOP – Absztrakt osztályok és interfészek",
    "publishedAt": "2015-01-19",
    "excerpt": "Az előző OOP részben átvettük hogyan is kell osztályokat definiálni, példányosítani, valamint az access modifier kulcsszavakat. Mostani részünkben az absztrakt osztályokat és interfészeket vesszük…",
    "oldPermalink": "/2015/01/19/php-oop-absztrakt-osztalyok-es-interfeszek/"
  },
  {
    "slug": "szabjuk-at-a-szerverunket-1-resz",
    "title": "Szabjuk át a szerverünket – 1. rész",
    "publishedAt": "2015-01-18",
    "excerpt": "Ha az ember webfejlesztéssel foglalkozik, óhatatlan, hogy előbb-utóbb elcsábuljon, netán rendszergizda híján rákényszerüljön, hogy a szerverüzemeltetésbe belekóstoljon. Itt most csak és kizárólag…",
    "oldPermalink": "/2015/01/18/szabjuk-szerverunket-1-resz/"
  },
  {
    "slug": "we-want-you",
    "title": "We want you!",
    "publishedAt": "2015-01-13",
    "excerpt": "Ha úgy érzed, hogy akadnak olyan témák a programozás területén, amikhez értesz és a tudásodat - netán a problémákat, amikkel szembesültél a megoldás során -, meg akarod osztani másokkal, akkor írj…",
    "oldPermalink": "/2015/01/13/we-want-you/"
  },
  {
    "slug": "php-model-view-controller",
    "title": "PHP Model-View-Controller",
    "publishedAt": "2015-01-09",
    "excerpt": "Annyira divatos kifejezés az MVC manapság, ellenben amikor valaki megpróbálja elmagyarázni, akkor eszembe jut, hogy ezt talán lehetne másképp is értelmezni. Az MVC a címben is szereplő hármast, a…",
    "oldPermalink": "/2015/01/09/php-model-view-controller/"
  },
  {
    "slug": "php-oop-mielott-barmibe-kezdenenk",
    "title": "PHP OOP – mielőtt bármibe kezdenénk",
    "publishedAt": "2015-01-08",
    "excerpt": "Rövidke PHP-s fórumokon lebzselő pályafutásom alatt a legtöbb kérdés az objektum-orientált programozás témaköréből került ki és, habár száznál is több oldalt lehet találni az interneten, talán ez a…",
    "oldPermalink": "/2015/01/08/php-oop-mielott-barmibe-kezdenenk/"
  },
  {
    "slug": "unit-test-meg-amit-akartok",
    "title": "Unit test meg amit akartok",
    "publishedAt": "2015-01-06",
    "excerpt": "A szoftverek tesztelésének több fajtája van, amik közül néhányról azok is hallhattak már, akik igazából nem foglalkoznak fejlesztéssel ( Ilyen például a béta-tesztelés). Ellenben van egy tesztelési…",
    "oldPermalink": "/2015/01/06/unit-test-meg-amit-akartok/"
  },
  {
    "slug": "daemon-idezes-php-ben-2-resz",
    "title": "Daemon idézés PHP-ben – 2. rész",
    "publishedAt": "2014-12-29",
    "excerpt": "Előző cikkemben végigvettünk pár alapfogalmat, ami a daemonokkal és a processekkel kapcsolatos, de mindeddig nem derült fény arra, miért is érdemes PHP nyelven ebbe belefogni. Rengetegen programoznak…",
    "oldPermalink": "/2014/12/29/daemon-idezes-php-ben-2-resz/"
  },
  {
    "slug": "daemon-idezes-php-ben",
    "title": "Daemon idézés PHP-ben",
    "publishedAt": "2014-12-24",
    "excerpt": "A daemon, <dela mitológiákban az istenek és az emberek között állnak és </del a multitask rendszerekben használatos elnevezés azokra a programokra, amik a háttérben futnak, ahelyett, hogy direkt…",
    "oldPermalink": "/2014/12/24/daemon-idezes-php-ben/"
  },
  {
    "slug": "autoload-megoldasok-akkor-es-most",
    "title": "Autoload megoldások akkor és most",
    "publishedAt": "2014-12-21",
    "excerpt": "Az objektumorientáltság a PHP nyelvben is magával hordozta azt a tényt, hogy webalkalmazásaink egyre nagyobbra nőnek, és ahogy több és több könyvtárat használunk programunkhoz, az blokkok is…",
    "oldPermalink": "/2014/12/21/autoload-megoldasok-akkor-es/"
  },
  {
    "slug": "initial-commit",
    "title": "Initial commit",
    "publishedAt": "2014-12-20",
    "excerpt": "Ahogy minden projektet, ezt is elég nehéz elkezdeni, lévén ilyenkor 0 ember olvassa azt, amiket írok (ez remélhetőleg azért nőni fog :D) és ezért próbálok olyan témákat megragadni, ami a backend…",
    "oldPermalink": "/2014/12/20/initial-commit/"
  },
  {
    "slug": "php-a-kezdetek",
    "title": "PHP – A kezdetek",
    "publishedAt": "2014-12-20",
    "excerpt": "A PHP egy általános szerveroldali szkriptnyelv, ami tökéletes dinamikus weboldalak készítéséhez. Miért pont a PHP? Ha valaki a webfejlesztés sötét bugyraiba kíván ereszkedni, akkor több eszköz is…",
    "oldPermalink": "/2014/12/20/php-a-kezdetek/"
  }
]
