/**
 * AUTO-GENERATED by scripts/migrate-jekyll-archive.ts.
 * Maps each old Jekyll permalink (already-indexed by Google) to its new archive slug.
 * Do not hand-edit; re-run the script if the source content needs to change.
 */
export interface ArchiveRedirect {
  path: string
  slug: string
}

export const archiveRedirects: ArchiveRedirect[] = [
  {
    "path": "2023/01/09/az-elso-it-munkahely-4-resz",
    "slug": "az-elso-it-munkahely-4-resz"
  },
  {
    "path": "2023/01/05/az-elso-it-munkahely-3-resz",
    "slug": "az-elso-it-munkahely-3-resz"
  },
  {
    "path": "2022/12/21/az-elso-it-munkahely-2-resz",
    "slug": "az-elso-it-munkahely-2-resz"
  },
  {
    "path": "2022/11/28/az-elso-it-munkahely-1-resz",
    "slug": "az-elso-it-munkahely-1-resz"
  },
  {
    "path": "2022/09/06/dockerbe-zarva-1-resz",
    "slug": "dockerbe-zarva-1-resz"
  },
  {
    "path": "2022/03/24/terminalor-3-a-tmux-sessionok-lazadasa",
    "slug": "terminalor-3-a-tmux-sessionok-lazadasa"
  },
  {
    "path": "2022/03/15/elotte-utana-cv-refaktoralas-programozoknak-interju",
    "slug": "elotte-utana-cv-refaktoralas-programozoknak-interju"
  },
  {
    "path": "2022/01/28/a-portfolio-oldalak-szerepe-jelentosege-programozoknal-elso-munkahely",
    "slug": "a-portfolio-oldalak-szerepe-jelentosege-programozoknal-elso-munkahely"
  },
  {
    "path": "2021/09/30/docker-as-a-linux-service",
    "slug": "docker-as-a-linux-service"
  },
  {
    "path": "2021/03/16/menedzseljuk-a-sajat-gepunket",
    "slug": "menedzseljuk-a-sajat-gepunket"
  },
  {
    "path": "2020/12/29/php-8-0-az-opcache-tol-a-jit-ig-pt-ii",
    "slug": "php-80-az-opcache-tol-a-jit-ig-pt-ii"
  },
  {
    "path": "2020/12/24/php-8-0-az-opcache-tol-a-jit-ig-pt-1",
    "slug": "php-80-az-opcache-tol-a-jit-ig-pt-i"
  },
  {
    "path": "2020/10/12/asdf-a-fura-nevu-verziomenedzser",
    "slug": "asdf-a-fura-nevu-verziomenedzser"
  },
  {
    "path": "2020/07/01/vim-felturbozva",
    "slug": "vim-felturbozva"
  },
  {
    "path": "2020/04/12/ha-nem-ertessz-a-cobol",
    "slug": "ha-nem-ertesz-a-cobol"
  },
  {
    "path": "2020/04/11/k3s-kubernetes-egyszeruen",
    "slug": "k3s-kubernetes-egyszeruen"
  },
  {
    "path": "2020/04/04/kalandozasok-vimmel",
    "slug": "kalandozasok-vimmel"
  },
  {
    "path": "2020/03/15/teszt-f-i-r-s-t",
    "slug": "teszt-first"
  },
  {
    "path": "2020/02/12/klasszikus-class",
    "slug": "klasszikus-class"
  },
  {
    "path": "2020/01/16/a-teszteles-elveszett-elonye",
    "slug": "a-teszteles-elveszett-elonye"
  },
  {
    "path": "2020/01/15/java-kivetelek-checked-vagy-unchecked",
    "slug": "java-kivetelek-checked-vagy-unchecked"
  },
  {
    "path": "2020/01/09/a-dummy-a-spy-es-a-tiz-kicsi-stub",
    "slug": "a-dummy-a-spy-es-a-tiz-kicsi-stub"
  },
  {
    "path": "2018/06/01/amit-elronthatunk-az-adapter-patternel",
    "slug": "amit-elronthatunk-az-adapter-patternel"
  },
  {
    "path": "2017/10/28/inversion-of-layered-architecture",
    "slug": "inversion-of-layered-architecture"
  },
  {
    "path": "2017/10/15/hogy-indult-a-podcastunk",
    "slug": "hogy-indult-a-podcastunk"
  },
  {
    "path": "2017/07/27/videoportal-keszenletben",
    "slug": "videoportal-keszenletben"
  },
  {
    "path": "2017/05/13/logfajlok-pokla-2-mdc-keretrendszer-alatt",
    "slug": "logfajlok-pokla-2-mdc-keretrendszer-alatt"
  },
  {
    "path": "2017/05/11/mit-tegyunk-ha-mar-elvesztunk-logfajlokban",
    "slug": "mit-tegyunk-ha-mar-elvesztunk-a-logfajlokban"
  },
  {
    "path": "2017/04/12/sajat-cdn-kevesebb-mint-100-bol",
    "slug": "sajat-cdn-kevesebb-mint-100-bol"
  },
  {
    "path": "2017/02/18/circuit-breaker-avagy-mi-van-akkor-ha-nem-megy",
    "slug": "circuit-breaker-avagy-mi-van-akkor-ha-nem-megy"
  },
  {
    "path": "2017/02/06/laravel-dockerben",
    "slug": "laravel-dockerben"
  },
  {
    "path": "2017/01/30/vissza-jovobe-legacy-kodok",
    "slug": "vissza-a-jovobe-legacy-kodok"
  },
  {
    "path": "2017/01/23/soap-avagy-run-you-fools",
    "slug": "soap-avagy-run-you-fools"
  },
  {
    "path": "2017/01/21/ezeket-cikkeket-olvastatok-legtobben-2016-ban",
    "slug": "ezeket-a-cikkeket-olvastatok-legtobben-2016-ban"
  },
  {
    "path": "2017/01/15/konstrualjunk-web-api-t-passporticus-maximus",
    "slug": "konstrualjunk-web-api-t-passporticus-maximus"
  },
  {
    "path": "2016/12/31/php-docker-moge-bujva",
    "slug": "php-docker-moge-bujva"
  },
  {
    "path": "2016/12/27/pushbreaker-az-elet-ci-szerver-nelkul",
    "slug": "pushbreaker-az-elet-ci-szerver-nelkul"
  },
  {
    "path": "2016/12/22/oauth-2-0-apigility-modra",
    "slug": "oauth-20-apigility-modra"
  },
  {
    "path": "2016/12/20/hacklang-a-php-jovoje",
    "slug": "hacklang-a-php-jovoje"
  },
  {
    "path": "2016/12/19/konstrualjunk-web-api-t-3-resz",
    "slug": "konstrualjunk-web-api-t-2-felvonas"
  },
  {
    "path": "2016/12/04/angular-typescript-modra-3-resz",
    "slug": "angular-typescript-modra-3-resz"
  },
  {
    "path": "2016/12/04/sql-injectionrol-egyszeruen",
    "slug": "az-sql-injectionrol-egyszeruen"
  },
  {
    "path": "2016/11/09/learning-functional-programming-with-javascript-by-anjana-vakil",
    "slug": "learning-functional-programming-with-javascript-by-anjana-vakil"
  },
  {
    "path": "2016/11/08/angular-2-typescript-modra-2-resz",
    "slug": "angular-2-typescript-modra-2-resz"
  },
  {
    "path": "2016/10/30/az-objektum-orientalt-programozas-alapjai",
    "slug": "az-objektum-orientalt-programozas-alapjai"
  },
  {
    "path": "2016/10/18/megvaltoztathatatlan-objektumok",
    "slug": "megvaltoztathatatlan-objektumok"
  },
  {
    "path": "2016/10/10/angular-2-typescript-modra",
    "slug": "angular-2-typescript-modra-1-resz"
  },
  {
    "path": "2016/10/05/nyarvegi-nagytakaritas-weboldal-metaadatok",
    "slug": "nyarvegi-nagytakaritas-weboldal-metaadatok"
  },
  {
    "path": "2016/09/28/biztonsagos-jelszotarolas",
    "slug": "biztonsagos-jelszotarolas"
  },
  {
    "path": "2016/09/25/hypescript",
    "slug": "hypescript"
  },
  {
    "path": "2016/09/18/cross-platform-mobilosodas-2-resz",
    "slug": "cross-platform-mobilosodas-2-resz"
  },
  {
    "path": "2016/09/08/tiszta-infrastruktura-4-resz-magas-rendelkezesre-allasu-rendszer-ket-gepbol",
    "slug": "tiszta-infrastruktura-4-resz-magas-rendelkezesre-allasu-rendszer-ket-gepbol"
  },
  {
    "path": "2016/08/26/konstrualjunk-web-api-t-2",
    "slug": "konstrualjunk-web-api-t"
  },
  {
    "path": "2016/08/17/felreertett-programnyelvek-php",
    "slug": "felreertett-programnyelvek-php"
  },
  {
    "path": "2016/08/09/tiszta-infrastruktura-3-resz-mit-monitorozzak",
    "slug": "tiszta-infrastruktura-3-resz-mit-monitorozzak"
  },
  {
    "path": "2016/07/27/tiszta-infrastruktura-2-resz-bevezetes-a-rendszerautomatizalasba",
    "slug": "tiszta-infrastruktura-2-resz-bevezetes-a-rendszerautomatizalasba"
  },
  {
    "path": "2016/07/23/cross-platform-mobilosodas-1-resz",
    "slug": "cross-platform-mobilosodas-1-resz"
  },
  {
    "path": "2016/07/18/utoszo-a-tiszta-kod-sorozathoz",
    "slug": "utoszo-a-tiszta-kod-sorozathoz"
  },
  {
    "path": "2016/07/17/ne-allj-szoba-idegennel",
    "slug": "law-of-demeter-ne-allj-szoba-idegennel"
  },
  {
    "path": "2016/07/16/she-wants-the-di",
    "slug": "she-wants-the-di"
  },
  {
    "path": "2016/07/14/knitting-to-the-moon-a-holdraszallas-szamitogepei",
    "slug": "knitting-to-the-moon-a-holdraszallas-szamitogepei"
  },
  {
    "path": "2016/07/09/isp-interface-segregation-principle",
    "slug": "isp-interface-segregation-principle"
  },
  {
    "path": "2016/07/05/betonozas-3-0-liskov-es-haverok",
    "slug": "betonozas-30-liskov-es-a-haverok"
  },
  {
    "path": "2016/07/03/betonozas-2-resz-ocp",
    "slug": "betonozas-2-resz-ocp"
  },
  {
    "path": "2016/06/27/a-szilard-alapok",
    "slug": "a-szilard-alapok"
  },
  {
    "path": "2016/06/27/tiszta-infrastruktura-1-resz-ha-faj-csinald-gyakrabban",
    "slug": "tiszta-infrastruktura-1-resz-ha-faj-csinald-gyakrabban"
  },
  {
    "path": "2016/06/20/nem-kivanatos-alkalmazasok-uzemeltetese-linuxon",
    "slug": "nem-kivanatos-alkalmazasok-uzemeltetese-linuxon"
  },
  {
    "path": "2016/06/14/adatbazis-valtozasok-kezelese",
    "slug": "adatbazis-valtozasok-kezelese"
  },
  {
    "path": "2016/06/12/a-comment-on-how-we-learn-by-aino-vonge-corry",
    "slug": "a-comment-on-how-we-learn-by-aino-vonge-corry"
  },
  {
    "path": "2016/06/08/programming-is-terrible-lessons-learned-from-a-life-wasted",
    "slug": "programming-is-terrible-lessons-learned-from-a-life-wasted"
  },
  {
    "path": "2016/05/27/tiszta-kod-9-resz-helyezzuk-uzembe-a-blogot",
    "slug": "tiszta-kod-9-resz-helyezzuk-uzembe-a-blogot"
  },
  {
    "path": "2016/05/17/tiszta-kod-8-resz-egy-tiszta-kod-blog-kezdetei",
    "slug": "tiszta-kod-8-resz-egy-tiszta-kod-blog-kezdetei"
  },
  {
    "path": "2016/05/16/shifu-es-az-inversion-control",
    "slug": "az-oktrojator-pattern-es-az-ioc-container"
  },
  {
    "path": "2016/05/09/tiszta-kod-7-resz-mi-a-fene-az-a-dependency-injection-container",
    "slug": "tiszta-kod-7-resz-mi-a-fene-az-a-dependency-injection-container"
  },
  {
    "path": "2016/05/08/repository-k-verziokovetesen-tul",
    "slug": "repository-k-a-verziokovetesen-is-tul"
  },
  {
    "path": "2016/05/07/the-future-of-programming-by-robert-c-martin",
    "slug": "the-future-of-programming-by-robert-c-martin"
  },
  {
    "path": "2016/05/04/az-imagetragick-biztonsagi-hiba-margojara",
    "slug": "az-imagetragick-biztonsagi-hiba-margojara"
  },
  {
    "path": "2016/05/02/tiszta-kod-6-resz-beszelnunk-kell-az-mvc-rol",
    "slug": "tiszta-kod-6-resz-beszelnunk-kell-az-mvc-rol"
  },
  {
    "path": "2016/04/28/diszitsuk-fel-wrappert",
    "slug": "diszitsuk-fel-a-wrappert"
  },
  {
    "path": "2016/04/26/tiszta-kod-5-resz-a-s-o-l-i-d-alapelvek",
    "slug": "tiszta-kod-5-resz-a-solid-alapelvek"
  },
  {
    "path": "2016/04/24/laravelre-at",
    "slug": "laravelre-at"
  },
  {
    "path": "2016/04/19/tiszta-kod-4-resz-tdd-a-gyakorlatban",
    "slug": "tiszta-kod-4-resz-tdd-a-gyakorlatban"
  },
  {
    "path": "2016/04/17/eureka",
    "slug": "eureka"
  },
  {
    "path": "2016/04/07/tiszta-kod-2-resz-teszteljunk-tdd-vel",
    "slug": "tiszta-kod-2-resz-teszteljunk-tdd-vel"
  },
  {
    "path": "2016/04/04/facade-pattern",
    "slug": "facade-pattern"
  },
  {
    "path": "2016/04/04/the-transformation-priority-premise",
    "slug": "the-transformation-priority-premise-by-robert-c-martin"
  },
  {
    "path": "2016/03/30/a-microservice-hype",
    "slug": "a-microservice-hype"
  },
  {
    "path": "2016/03/29/tiszta-kod-1-resz-teszteljek-vagy-ne-teszteljek",
    "slug": "tiszta-kod-1-resz-teszteljek-vagy-ne-teszteljek"
  },
  {
    "path": "2016/03/25/agility-and-architecture-by-robert-c-martin",
    "slug": "agility-and-architecture-by-robert-c-martin"
  },
  {
    "path": "2016/03/24/hogyan-mukodik-az-internet-3-resz-az-icmp-a-udp-es-a-tcp",
    "slug": "hogyan-mukodik-az-internet-3-resz-az-icmp-a-udp-es-a-tcp"
  },
  {
    "path": "2016/03/24/refactoring-a-javabol",
    "slug": "refactoring-a-javabol"
  },
  {
    "path": "2016/03/18/steal-everything-kill-everyone-cause-total-financial-ruin-by-jayson-e-street",
    "slug": "steal-everything-kill-everyone-cause-total-financial-ruin-by-jayson-e-street"
  },
  {
    "path": "2016/03/17/professional-software-development-by-robert-c-martin",
    "slug": "professional-software-development-by-robert-c-martin"
  },
  {
    "path": "2016/03/16/low-level-debugolas-2-resz-halozati-eszkozok",
    "slug": "low-level-debugolas-2-resz-halozati-eszkozok"
  },
  {
    "path": "2016/03/14/core-design-principles-for-software-developers-by-venkat-subramaniam",
    "slug": "core-design-principles-for-software-developers-by-venkat-subramaniam"
  },
  {
    "path": "2016/03/08/hogyan-mukodik-az-internet-2-resz-az-internet-protokoll",
    "slug": "hogyan-mukodik-az-internet-2-resz-az-internet-protokoll"
  },
  {
    "path": "2016/03/07/115-batshit-stupid-things-you-can-put-on-the-internet-by-dan-tentler",
    "slug": "115-batshit-stupid-things-you-can-put-on-the-internet-by-dan-tentler"
  },
  {
    "path": "2016/02/29/5-ok-hogy-miert-felejtsd-el-az-ftp-t",
    "slug": "5-ok-hogy-miert-felejtsd-el-az-ftp-t"
  },
  {
    "path": "2016/02/29/az-automatizalt-rendszergazda",
    "slug": "az-automatizalt-rendszergazda"
  },
  {
    "path": "2016/02/29/dont-look-for-things-by-misko-hevery",
    "slug": "dont-look-for-things-by-misko-hevery"
  },
  {
    "path": "2016/02/29/hogyan-mukodik-az-internet-1-resz-az-ethernet",
    "slug": "hogyan-mukodik-az-internet-1-resz-az-ethernet"
  },
  {
    "path": "2016/02/29/how-to-design-a-good-api",
    "slug": "how-to-design-a-good-api-and-why-it-matters"
  },
  {
    "path": "2016/02/29/idokezeles-a-programozasban",
    "slug": "idokezeles-a-programozasban"
  },
  {
    "path": "2016/02/29/low-level-debugolas-1-resz-strace",
    "slug": "low-level-debugolas-1-resz-strace"
  },
  {
    "path": "2016/02/29/the-silver-bullet-syndrome-by-hadi-hariri",
    "slug": "the-silver-bullet-syndrome-by-hadi-hariri"
  },
  {
    "path": "2016/02/29/transzparencia-a-fizetesekben-interju",
    "slug": "transzparencia-a-fizetesekben"
  },
  {
    "path": "2016/02/29/unit-testing-by-misko-hevery",
    "slug": "unit-testing-by-misko-hevery"
  },
  {
    "path": "2016/02/07/laravel-5-tele-a-puttonyt",
    "slug": "partizankodas-3-tele-a-puttonyt"
  },
  {
    "path": "2016/01/31/helyszini-teszteles-2016-februar",
    "slug": "helyszini-teszt-2016-februar"
  },
  {
    "path": "2016/01/17/partizankodas-2-csomagolastechnika",
    "slug": "partizankodas-2-csomagolastechnika"
  },
  {
    "path": "2016/01/11/partizankodjunk-a-laravel-5-el",
    "slug": "partizankodjunk-a-laravel-5-el"
  },
  {
    "path": "2016/01/03/uj-ev-uj-temakor",
    "slug": "uj-ev-uj-temakor"
  },
  {
    "path": "2015/12/31/2015-review",
    "slug": "2015-review"
  },
  {
    "path": "2015/12/30/javascript-pakk-3-kinek-kell-a-js",
    "slug": "javascript-pakk-3-kinek-kell-a-js"
  },
  {
    "path": "2015/12/26/javaspricc-pakk-2-babel",
    "slug": "javaspricc-pakk-2-babel"
  },
  {
    "path": "2015/12/24/javascript-pakk-no-1-ecmascript-6",
    "slug": "javascript-pakk-no-1-ecmascript-6"
  },
  {
    "path": "2015/12/19/back-up-me-baby-one-more-time",
    "slug": "back-up-me-baby-one-more-time"
  },
  {
    "path": "2015/12/17/scooter-back-it-up",
    "slug": "scooter-back-it-up"
  },
  {
    "path": "2015/12/07/backup-ftw",
    "slug": "backup-ftw"
  },
  {
    "path": "2015/11/10/eloben-jelentkezunk-a-helyszinrol",
    "slug": "eloben-jelentkezunk-a-helyszinrol"
  },
  {
    "path": "2015/11/01/laravel-5-0-request-es-response",
    "slug": "laravel-50-request-es-response"
  },
  {
    "path": "2015/10/25/dokkolnam-dokkolnam",
    "slug": "dokkolnam-dokkolnam"
  },
  {
    "path": "2015/10/13/martin-papa-szinrelep-az-adataink",
    "slug": "martin-papa-szinrelep-az-adataink"
  },
  {
    "path": "2015/09/25/eredmenyhirdetes",
    "slug": "eredmenyhirdetes"
  },
  {
    "path": "2015/09/03/strategy-pattern-az-objektumok-lazadasa",
    "slug": "strategy-pattern-az-objektumok-lazadasa"
  },
  {
    "path": "2015/08/30/command-pattern-es-a-penzugyszamvitel",
    "slug": "command-pattern-es-a-penzugyszamvitel"
  },
  {
    "path": "2015/08/25/controller-es-middleware-a-ket-jobarat",
    "slug": "controller-es-middleware-a-ket-jobarat"
  },
  {
    "path": "2015/08/24/martin-papa-strikes-back-domain-logic-2",
    "slug": "martin-papa-strikes-back-domain-logic-2"
  },
  {
    "path": "2015/08/22/martin-papa-kozbelep-domain-logic",
    "slug": "martin-papa-kozbelep-domain-logic"
  },
  {
    "path": "2015/08/18/gittegylet-4-jegyeket-berleteket",
    "slug": "gittegylet-4-jegyeket-berleteket"
  },
  {
    "path": "2015/08/17/nyelvtani-alapok-lara-val-laravel",
    "slug": "nyelvtani-alapok-lara-vallaravel"
  },
  {
    "path": "2015/08/02/zendules-1-resz-skeleton-application",
    "slug": "zendules-1-resz-skeleton-application"
  },
  {
    "path": "2015/07/06/termiterator-2",
    "slug": "termiterator-2"
  },
  {
    "path": "2015/06/16/observer-pattern-es-a-robotics-facility",
    "slug": "observer-pattern-es-a-robotics-facility"
  },
  {
    "path": "2015/05/17/javascript-oop",
    "slug": "javascript-oop"
  },
  {
    "path": "2015/05/01/husveti-kulonkiadas-amqp",
    "slug": "husveti-kulonkiadas-amqp"
  },
  {
    "path": "2015/04/01/a-gyarba-vissza-e-servicelocator",
    "slug": "a-gyarba-vissza-e-servicelocator"
  },
  {
    "path": "2015/03/27/git-3-under-the-hood",
    "slug": "git-3-under-the-hood"
  },
  {
    "path": "2015/03/23/gittegylet-2-a-karosszerialakatos-visszavag",
    "slug": "gittegylet-2-a-karosszerialakatos-visszavag"
  },
  {
    "path": "2015/03/19/vagrant-es-rio-de-janeiro",
    "slug": "vagrant-es-rio-de-janeiro"
  },
  {
    "path": "2015/03/12/composer-a-php-fejlesztok-kedvenc-zeneszerzoje",
    "slug": "composer-a-php-fejlesztok-kedvenc-zeneszerzoje"
  },
  {
    "path": "2015/03/12/memcached-serve-it-or-do-not-serve-it-but-serve-it-fast",
    "slug": "memcached-serve-it-or-do-not-serve-it-but-serve-it-fast"
  },
  {
    "path": "2015/03/06/kincs-ami-nincs-2-resz",
    "slug": "kincs-ami-nincs-2-resz"
  },
  {
    "path": "2015/03/03/anulu-elete-pongo-mongodb-szigeten",
    "slug": "anulu-elete-pongo-mongodb-szigeten"
  },
  {
    "path": "2015/02/28/long-polling-sse-websocket-mmx-es-mas-szep-szakszavak",
    "slug": "long-polling-sse-websocket-mmx-es-mas-szep-szakszavak"
  },
  {
    "path": "2015/02/24/de-jegyezd-meg-jol-mig-a-fold-kerek-mindig-lesznek-nevterek",
    "slug": "de-jegyezd-meg-jol-mig-a-fold-kerek-mindig-lesznek-nevterek"
  },
  {
    "path": "2015/02/22/a-git-tegylet",
    "slug": "a-git-tegylet"
  },
  {
    "path": "2015/02/19/a-proxy-pattern-szerepe-az-okori-romaban",
    "slug": "a-proxy-pattern-szerepe-az-okori-romaban"
  },
  {
    "path": "2015/02/16/builder-pattern-es-7-hardveres",
    "slug": "builder-pattern-es-a-7-hardveres"
  },
  {
    "path": "2015/02/14/keresre-sessionmanager",
    "slug": "keresre-sessionmanager"
  },
  {
    "path": "2015/02/13/its-a-kind-of-__magic",
    "slug": "its-a-kind-of-magic"
  },
  {
    "path": "2015/02/10/az-md5-art-az-egeszsegnek",
    "slug": "az-md5-art-az-egeszsegnek"
  },
  {
    "path": "2015/02/05/cache-avagy-dugikeszletek",
    "slug": "cache-avagy-a-dugikeszletek"
  },
  {
    "path": "2015/02/01/keresooptimalizalas-maskepp-opcache",
    "slug": "keresooptimalizalas-maskepp-opcache"
  },
  {
    "path": "2015/01/30/onvedelmi-gyakorlatok-csrf-es-session-hijacking",
    "slug": "onvedelmi-gyakorlatok-csrf-es-session-hijacking"
  },
  {
    "path": "2015/01/29/tervezesi-mintak-adapter-pattern",
    "slug": "tervezesi-mintak-adapter-pattern"
  },
  {
    "path": "2015/01/26/prototype-pattern-ii-klonok-tamadasa",
    "slug": "prototype-pattern-ii-a-klonok-tamadasa"
  },
  {
    "path": "2015/01/24/factory-pattern-munkanak-vege-kijossz",
    "slug": "factory-pattern-a-munkanak-vege-kijossz-a"
  },
  {
    "path": "2015/01/24/tervezesi-mintak-singleton-es-het-torpe",
    "slug": "tervezesi-mintak-singleton-es-a-het-torpe"
  },
  {
    "path": "2015/01/22/onvedelmi-gyakorlatok-1-resz",
    "slug": "onvedelmi-gyakorlatok-1-resz"
  },
  {
    "path": "2015/01/21/oops-avagy-dependency-injection-praktikak",
    "slug": "oops-i-did-it-again-avagy-dependency-injection-praktikak"
  },
  {
    "path": "2015/01/19/php-oop-absztrakt-osztalyok-es-interfeszek",
    "slug": "php-oop-absztrakt-osztalyok-es-interfeszek"
  },
  {
    "path": "2015/01/18/szabjuk-szerverunket-1-resz",
    "slug": "szabjuk-at-a-szerverunket-1-resz"
  },
  {
    "path": "2015/01/13/we-want-you",
    "slug": "we-want-you"
  },
  {
    "path": "2015/01/09/php-model-view-controller",
    "slug": "php-model-view-controller"
  },
  {
    "path": "2015/01/08/php-oop-mielott-barmibe-kezdenenk",
    "slug": "php-oop-mielott-barmibe-kezdenenk"
  },
  {
    "path": "2015/01/06/unit-test-meg-amit-akartok",
    "slug": "unit-test-meg-amit-akartok"
  },
  {
    "path": "2014/12/29/daemon-idezes-php-ben-2-resz",
    "slug": "daemon-idezes-php-ben-2-resz"
  },
  {
    "path": "2014/12/24/daemon-idezes-php-ben",
    "slug": "daemon-idezes-php-ben"
  },
  {
    "path": "2014/12/21/autoload-megoldasok-akkor-es",
    "slug": "autoload-megoldasok-akkor-es-most"
  },
  {
    "path": "2014/12/20/initial-commit",
    "slug": "initial-commit"
  },
  {
    "path": "2014/12/20/php-a-kezdetek",
    "slug": "php-a-kezdetek"
  }
]
